---
title: "Research Fairness and Research Intergrity: A cross-sectional surevy"
author: "Dr Joseph B Sempa"
date: "`r Sys.Date()`"
output:
  word_document:
    fig_caption: yes
    toc: yes
  pdf_document:
    fig_caption: yes
    toc: yes
  html_document:
    fig_caption: yes
    toc: yes
  html_notebook:
    toc: yes
always_allow_html: true
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(results = 'asis')
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(tinytex)
library(gmodels)
library(readxl)
library(gtsummary)
library(caret)
library(leaps)
library(MASS)
library(predtools)
library(randomForest)
library(mice)
library(psfmi)
library(survey)
```


```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# library(readr)
final_dataset <- read_csv("final_dataset.csv")[-c(19,27,45,122),] %>%
  mutate(`Which of the following best describes you?` = as.factor(ifelse(`Which of the following best describes you?`=='Other (please specify)', 'Researcher from the Global North',  `Which of the following best describes you?`)))
# pilotstudy_dataset <-
#   survey::svydesign(
#     id = ~`Respondent ID`,
#     # weights = ~pw, # target proportion/ actual sample proportion
#     data = dataset#,
#     # fpc = ~fpc # ((Population size-sample size)/(population size-1))^(1/2)
#   )
# negative questions for responsible research practices: 1,3,4,5,7,8,10,11,15,18,19
# negative questions for fair research practices: 1,2,10,12,13
final_dataset <- final_dataset %>%
  mutate(
    rpq1 = case_when(
      `responsible research Practices_q1` == 'Never' ~ 7,
      `responsible research Practices_q1` == 'Very Rarely' ~ 6,
      `responsible research Practices_q1` == 'Rarely' ~ 5,
      `responsible research Practices_q1` == 'Occasionally' ~ 4,
      `responsible research Practices_q1` == 'Frequently' ~ 3,
      `responsible research Practices_q1` == 'Very Frequently' ~ 2,
      `responsible research Practices_q1` == 'Always' ~ 1
    ),
    rpq2 = case_when(
      `responsible research Practices_q2` == 'Never' ~ 1,
      `responsible research Practices_q2` == 'Very Rarely' ~ 2,
      `responsible research Practices_q2` == 'Rarely' ~ 3,
      `responsible research Practices_q2` == 'Occasionally' ~ 4,
      `responsible research Practices_q2` == 'Frequently' ~ 5,
      `responsible research Practices_q2` == 'Very Frequently' ~ 6,
      `responsible research Practices_q2` == 'Always' ~ 7
    ),
    rpq3 = case_when(
      `responsible research Practices_q3` == 'Never' ~ 7,
      `responsible research Practices_q3` == 'Very Rarely' ~ 6,
      `responsible research Practices_q3` == 'Rarely' ~ 5,
      `responsible research Practices_q3` == 'Occasionally' ~ 4,
      `responsible research Practices_q3` == 'Frequently' ~ 3,
      `responsible research Practices_q3` == 'Very Frequently' ~ 2,
      `responsible research Practices_q3` == 'Always' ~ 1
    ),
    rpq4 = case_when(
      `responsible research Practices_q4` == 'Never' ~ 7,
      `responsible research Practices_q4` == 'Very Rarely' ~ 6,
      `responsible research Practices_q4` == 'Rarely' ~ 5,
      `responsible research Practices_q4` == 'Occasionally' ~ 4,
      `responsible research Practices_q4` == 'Frequently' ~ 3,
      `responsible research Practices_q4` == 'Very Frequently' ~ 2,
      `responsible research Practices_q4` == 'Always' ~ 1
    ),
    rpq5 = case_when(
      `responsible research Practices_q5` == 'Never' ~ 7,
      `responsible research Practices_q5` == 'Very Rarely' ~ 6,
      `responsible research Practices_q5` == 'Rarely' ~ 5,
      `responsible research Practices_q5` == 'Occasionally' ~ 4,
      `responsible research Practices_q5` == 'Frequently' ~ 3,
      `responsible research Practices_q5` == 'Very Frequently' ~ 2,
      `responsible research Practices_q5` == 'Always' ~ 1
    ),
    rpq6 = case_when(
      `responsible research Practices_q6` == 'Never' ~ 1,
      `responsible research Practices_q6` == 'Very Rarely' ~ 2,
      `responsible research Practices_q6` == 'Rarely' ~ 3,
      `responsible research Practices_q6` == 'Occasionally' ~ 4,
      `responsible research Practices_q6` == 'Frequently' ~ 5,
      `responsible research Practices_q6` == 'Very Frequently' ~ 6,
      `responsible research Practices_q6` == 'Always' ~ 7
    ),
    rpq7 = case_when(
      `responsible research Practices_q7` == 'Never' ~ 7,
      `responsible research Practices_q7` == 'Very Rarely' ~ 6,
      `responsible research Practices_q7` == 'Rarely' ~ 5,
      `responsible research Practices_q7` == 'Occasionally' ~ 4,
      `responsible research Practices_q7` == 'Frequently' ~ 3,
      `responsible research Practices_q7` == 'Very Frequently' ~ 2,
      `responsible research Practices_q7` == 'Always' ~ 1
    ),
    rpq8 = case_when(
      `responsible research Practices_q8` == 'Never' ~ 7,
      `responsible research Practices_q8` == 'Very Rarely' ~ 6,
      `responsible research Practices_q8` == 'Rarely' ~ 5,
      `responsible research Practices_q8` == 'Occasionally' ~ 4,
      `responsible research Practices_q8` == 'Frequently' ~ 3,
      `responsible research Practices_q8` == 'Very Frequently' ~ 2,
      `responsible research Practices_q8` == 'Always' ~ 1
    ),
    rpq9 = case_when(
      `responsible research Practices_q9` == 'Never' ~ 1,
      `responsible research Practices_q9` == 'Very Rarely' ~ 2,
      `responsible research Practices_q9` == 'Rarely' ~ 3,
      `responsible research Practices_q9` == 'Occasionally' ~ 4,
      `responsible research Practices_q9` == 'Frequently' ~ 5,
      `responsible research Practices_q9` == 'Very Frequently' ~ 6,
      `responsible research Practices_q9` == 'Always' ~ 7
    ),
    rpq10 = case_when(
      `responsible research Practices_q10` == 'Never' ~ 7,
      `responsible research Practices_q10` == 'Very Rarely' ~ 6,
      `responsible research Practices_q10` == 'Rarely' ~ 5,
      `responsible research Practices_q10` == 'Occasionally' ~ 4,
      `responsible research Practices_q10` == 'Frequently' ~ 3,
      `responsible research Practices_q10` == 'Very Frequently' ~ 2,
      `responsible research Practices_q10` == 'Always' ~ 1
    ),
    rpq11 = case_when(
      `responsible research Practices_q11` == 'Never' ~ 7,
      `responsible research Practices_q11` == 'Very Rarely' ~ 6,
      `responsible research Practices_q11` == 'Rarely' ~ 5,
      `responsible research Practices_q11` == 'Occasionally' ~ 4,
      `responsible research Practices_q11` == 'Frequently' ~ 3,
      `responsible research Practices_q11` == 'Very Frequently' ~ 2,
      `responsible research Practices_q11` == 'Always' ~ 1
    ),
    rpq12 = case_when(
      `responsible research Practices_q12` == 'Never' ~ 1,
      `responsible research Practices_q12` == 'Very Rarely' ~ 2,
      `responsible research Practices_q12` == 'Rarely' ~ 3,
      `responsible research Practices_q12` == 'Occasionally' ~ 4,
      `responsible research Practices_q12` == 'Frequently' ~ 5,
      `responsible research Practices_q12` == 'Very Frequently' ~ 6,
      `responsible research Practices_q12` == 'Always' ~ 7
    ),
    rpq13 = case_when(
      `responsible research Practices_q13` == 'Never' ~ 1,
      `responsible research Practices_q13` == 'Very Rarely' ~ 2,
      `responsible research Practices_q13` == 'Rarely' ~ 3,
      `responsible research Practices_q13` == 'Occasionally' ~ 4,
      `responsible research Practices_q13` == 'Frequently' ~ 5,
      `responsible research Practices_q13` == 'Very Frequently' ~ 6,
      `responsible research Practices_q13` == 'Always' ~ 7
    ),
    rpq14 = case_when(
      `responsible research Practices_q14` == 'Never' ~ 1,
      `responsible research Practices_q14` == 'Very Rarely' ~ 2,
      `responsible research Practices_q14` == 'Rarely' ~ 3,
      `responsible research Practices_q14` == 'Occasionally' ~ 4,
      `responsible research Practices_q14` == 'Frequently' ~ 5,
      `responsible research Practices_q14` == 'Very Frequently' ~ 6,
      `responsible research Practices_q14` == 'Always' ~ 7
    ),
    rpq15 = case_when(
      `responsible research Practices_q15` == 'Never' ~ 7,
      `responsible research Practices_q15` == 'Very Rarely' ~ 6,
      `responsible research Practices_q15` == 'Rarely' ~ 5,
      `responsible research Practices_q15` == 'Occasionally' ~ 4,
      `responsible research Practices_q15` == 'Frequently' ~ 3,
      `responsible research Practices_q15` == 'Very Frequently' ~ 2,
      `responsible research Practices_q15` == 'Always' ~ 1
    ),
    rpq16 = case_when(
      `responsible research Practices_q16` == 'Never' ~ 1,
      `responsible research Practices_q16` == 'Very Rarely' ~ 2,
      `responsible research Practices_q16` == 'Rarely' ~ 3,
      `responsible research Practices_q16` == 'Occasionally' ~ 4,
      `responsible research Practices_q16` == 'Frequently' ~ 5,
      `responsible research Practices_q16` == 'Very Frequently' ~ 6,
      `responsible research Practices_q16` == 'Always' ~ 7
    ),
    rpq17 = case_when(
      `responsible research Practices_q17` == 'Never' ~ 1,
      `responsible research Practices_q17` == 'Very Rarely' ~ 2,
      `responsible research Practices_q17` == 'Rarely' ~ 3,
      `responsible research Practices_q17` == 'Occasionally' ~ 4,
      `responsible research Practices_q17` == 'Frequently' ~ 5,
      `responsible research Practices_q17` == 'Very Frequently' ~ 6,
      `responsible research Practices_q17` == 'Always' ~ 7
    ),
    rpq18 = case_when(
      `responsible research Practices_q18` == 'Never' ~ 7,
      `responsible research Practices_q18` == 'Very Rarely' ~ 6,
      `responsible research Practices_q18` == 'Rarely' ~ 5,
      `responsible research Practices_q18` == 'Occasionally' ~ 4,
      `responsible research Practices_q18` == 'Frequently' ~ 3,
      `responsible research Practices_q18` == 'Very Frequently' ~ 2,
      `responsible research Practices_q18` == 'Always' ~ 1
    ),
    rpq19 = case_when(
      `responsible research Practices_q19` == 'Never' ~ 7,
      `responsible research Practices_q19` == 'Very Rarely' ~ 6,
      `responsible research Practices_q19` == 'Rarely' ~ 5,
      `responsible research Practices_q19` == 'Occasionally' ~ 4,
      `responsible research Practices_q19` == 'Frequently' ~ 3,
      `responsible research Practices_q19` == 'Very Frequently' ~ 2,
      `responsible research Practices_q19` == 'Always' ~ 1
    ),
    rpq20 = case_when(
      `responsible research Practices_q20` == 'Never' ~ 1,
      `responsible research Practices_q20` == 'Very Rarely' ~ 2,
      `responsible research Practices_q20` == 'Rarely' ~ 3,
      `responsible research Practices_q20` == 'Occasionally' ~ 4,
      `responsible research Practices_q20` == 'Frequently' ~ 5,
      `responsible research Practices_q20` == 'Very Frequently' ~ 6,
      `responsible research Practices_q20` == 'Always' ~ 7
    )
  ) %>% # 1,2,10,12,13
  mutate(
    fpq1 = case_when(
      `fair research practices_q1` == 'Never' ~ 7,
      `fair research practices_q1` == 'Very Rarely' ~ 6,
      `fair research practices_q1` == 'Rarely' ~ 5,
      `fair research practices_q1` == 'Occasionally' ~ 4,
      `fair research practices_q1` == 'Frequently' ~ 3,
      `fair research practices_q1` == 'Very Frequently' ~ 2,
      `fair research practices_q1` == 'Always' ~ 1
    ),
    fpq2 = case_when(
      `fair research practices_q2` == 'Never' ~ 7,
      `fair research practices_q2` == 'Very Rarely' ~ 6,
      `fair research practices_q2` == 'Rarely' ~ 5,
      `fair research practices_q2` == 'Occasionally' ~ 4,
      `fair research practices_q2` == 'Frequently' ~ 3,
      `fair research practices_q2` == 'Very Frequently' ~ 2,
      `fair research practices_q2` == 'Always' ~ 1
    ),
    fpq3 = case_when(
      `fair research practices_q3` == 'Never' ~ 1,
      `fair research practices_q3` == 'Very Rarely' ~ 2,
      `fair research practices_q3` == 'Rarely' ~ 3,
      `fair research practices_q3` == 'Occasionally' ~ 4,
      `fair research practices_q3` == 'Frequently' ~ 5,
      `fair research practices_q3` == 'Very Frequently' ~ 6,
      `fair research practices_q3` == 'Always' ~ 7
    ),
    fpq4 = case_when(
      `fair research practices_q4` == 'Never' ~ 1,
      `fair research practices_q4` == 'Very Rarely' ~ 2,
      `fair research practices_q4` == 'Rarely' ~ 3,
      `fair research practices_q4` == 'Occasionally' ~ 4,
      `fair research practices_q4` == 'Frequently' ~ 5,
      `fair research practices_q4` == 'Very Frequently' ~ 6,
      `fair research practices_q4` == 'Always' ~ 7
    ),
    fpq5 = case_when(
      `fair research practices_q5` == 'Never' ~ 1,
      `fair research practices_q5` == 'Very Rarely' ~ 2,
      `fair research practices_q5` == 'Rarely' ~ 3,
      `fair research practices_q5` == 'Occasionally' ~ 4,
      `fair research practices_q5` == 'Frequently' ~ 5,
      `fair research practices_q5` == 'Very Frequently' ~ 6,
      `fair research practices_q5` == 'Always' ~ 7
    ),
    fpq6 = case_when(
      `fair research practices_q6` == 'Never' ~ 1,
      `fair research practices_q6` == 'Very Rarely' ~ 2,
      `fair research practices_q6` == 'Rarely' ~ 3,
      `fair research practices_q6` == 'Occasionally' ~ 4,
      `fair research practices_q6` == 'Frequently' ~ 5,
      `fair research practices_q6` == 'Very Frequently' ~ 6,
      `fair research practices_q6` == 'Always' ~ 7
    ),
    fpq7 = case_when(
      `fair research practices_q7` == 'Never' ~ 1,
      `fair research practices_q7` == 'Very Rarely' ~ 2,
      `fair research practices_q7` == 'Rarely' ~ 3,
      `fair research practices_q7` == 'Occasionally' ~ 4,
      `fair research practices_q7` == 'Frequently' ~ 5,
      `fair research practices_q7` == 'Very Frequently' ~ 6,
      `fair research practices_q7` == 'Always' ~ 7
    ),
    fpq8 = case_when(
      `fair research practices_q8` == 'Never' ~ 1,
      `fair research practices_q8` == 'Very Rarely' ~ 2,
      `fair research practices_q8` == 'Rarely' ~ 3,
      `fair research practices_q8` == 'Occasionally' ~ 4,
      `fair research practices_q8` == 'Frequently' ~ 5,
      `fair research practices_q8` == 'Very Frequently' ~ 6,
      `fair research practices_q8` == 'Always' ~ 7
    ),
    fpq9 = case_when(
      `fair research practices_q9` == 'Never' ~ 1,
      `fair research practices_q9` == 'Very Rarely' ~ 2,
      `fair research practices_q9` == 'Rarely' ~ 3,
      `fair research practices_q9` == 'Occasionally' ~ 4,
      `fair research practices_q9` == 'Frequently' ~ 5,
      `fair research practices_q9` == 'Very Frequently' ~ 6,
      `fair research practices_q9` == 'Always' ~ 7
    ),
    fpq10 = case_when(
      `fair research practices_q10` == 'Never' ~ 7,
      `fair research practices_q10` == 'Very Rarely' ~ 6,
      `fair research practices_q10` == 'Rarely' ~ 5,
      `fair research practices_q10` == 'Occasionally' ~ 4,
      `fair research practices_q10` == 'Frequently' ~ 3,
      `fair research practices_q10` == 'Very Frequently' ~ 2,
      `fair research practices_q10` == 'Always' ~ 1
    ),
    fpq11 = case_when(
      `fair research practices_q11` == 'Never' ~ 1,
      `fair research practices_q11` == 'Very Rarely' ~ 2,
      `fair research practices_q11` == 'Rarely' ~ 3,
      `fair research practices_q11` == 'Occasionally' ~ 4,
      `fair research practices_q11` == 'Frequently' ~ 5,
      `fair research practices_q11` == 'Very Frequently' ~ 6,
      `fair research practices_q11` == 'Always' ~ 7
    ),
    fpq12 = case_when(
      `fair research practices_q12` == 'Never' ~ 7,
      `fair research practices_q12` == 'Very Rarely' ~ 6,
      `fair research practices_q12` == 'Rarely' ~ 5,
      `fair research practices_q12` == 'Occasionally' ~ 4,
      `fair research practices_q12` == 'Frequently' ~ 3,
      `fair research practices_q12` == 'Very Frequently' ~ 2,
      `fair research practices_q12` == 'Always' ~ 1
    ),
    fpq13 = case_when(
      `fair research practices_q13` == 'Never' ~ 7,
      `fair research practices_q13` == 'Very Rarely' ~ 6,
      `fair research practices_q13` == 'Rarely' ~ 5,
      `fair research practices_q13` == 'Occasionally' ~ 4,
      `fair research practices_q13` == 'Frequently' ~ 3,
      `fair research practices_q13` == 'Very Frequently' ~ 2,
      `fair research practices_q13` == 'Always' ~ 1
    ),
    fpq14 = case_when(
      `fair research practices_q14` == 'Never' ~ 1,
      `fair research practices_q14` == 'Very Rarely' ~ 2,
      `fair research practices_q14` == 'Rarely' ~ 3,
      `fair research practices_q14` == 'Occasionally' ~ 4,
      `fair research practices_q14` == 'Frequently' ~ 5,
      `fair research practices_q14` == 'Very Frequently' ~ 6,
      `fair research practices_q14` == 'Always' ~ 7
    ),
    fpq15 = case_when(
      `fair research practices_q15` == 'Never' ~ 1,
      `fair research practices_q15` == 'Very Rarely' ~ 2,
      `fair research practices_q15` == 'Rarely' ~ 3,
      `fair research practices_q15` == 'Occasionally' ~ 4,
      `fair research practices_q15` == 'Frequently' ~ 5,
      `fair research practices_q15` == 'Very Frequently' ~ 6,
      `fair research practices_q15` == 'Always' ~ 7
    ),
    fpq16 = case_when(
      `fair research practices_q16` == 'Never' ~ 1,
      `fair research practices_q16` == 'Very Rarely' ~ 2,
      `fair research practices_q16` == 'Rarely' ~ 3,
      `fair research practices_q16` == 'Occasionally' ~ 4,
      `fair research practices_q16` == 'Frequently' ~ 5,
      `fair research practices_q16` == 'Very Frequently' ~ 6,
      `fair research practices_q16` == 'Always' ~ 7
    ),
    fpq17 = case_when(
      `fair research practices_q17` == 'Never' ~ 1,
      `fair research practices_q17` == 'Very Rarely' ~ 2,
      `fair research practices_q17` == 'Rarely' ~ 3,
      `fair research practices_q17` == 'Occasionally' ~ 4,
      `fair research practices_q17` == 'Frequently' ~ 5,
      `fair research practices_q17` == 'Very Frequently' ~ 6,
      `fair research practices_q17` == 'Always' ~ 7
    ),
    fpq18 = case_when(
      `fair research practices_q18` == 'Never' ~ 1,
      `fair research practices_q18` == 'Very Rarely' ~ 2,
      `fair research practices_q18` == 'Rarely' ~ 3,
      `fair research practices_q18` == 'Occasionally' ~ 4,
      `fair research practices_q18` == 'Frequently' ~ 5,
      `fair research practices_q18` == 'Very Frequently' ~ 6,
      `fair research practices_q18` == 'Always' ~ 7
    ),
    fpq19 = case_when(
      `fair research practices_q19` == 'Never' ~ 1,
      `fair research practices_q19` == 'Very Rarely' ~ 2,
      `fair research practices_q19` == 'Rarely' ~ 3,
      `fair research practices_q19` == 'Occasionally' ~ 4,
      `fair research practices_q19` == 'Frequently' ~ 5,
      `fair research practices_q19` == 'Very Frequently' ~ 6,
      `fair research practices_q19` == 'Always' ~ 7
    ),
    fpq20 = case_when(
      `fair research practices_q20` == 'Never' ~ 1,
      `fair research practices_q20` == 'Very Rarely' ~ 2,
      `fair research practices_q20` == 'Rarely' ~ 3,
      `fair research practices_q20` == 'Occasionally' ~ 4,
      `fair research practices_q20` == 'Frequently' ~ 5,
      `fair research practices_q20` == 'Very Frequently' ~ 6,
      `fair research practices_q20` == 'Always' ~ 7
    )
  ) %>%
  mutate(
    `responsible research Practices score` = rpq1 + rpq2 + rpq3 + rpq4 + rpq5 + rpq6 + rpq7 + rpq8 + rpq9 + rpq10 + rpq11 + rpq12 + rpq13 + rpq14 + rpq15 + rpq16 + rpq17 + rpq18 + rpq19 + rpq20,
    `fair research practices score` = (fpq1 + fpq2 + fpq3 + fpq4 + fpq5 +fpq6 + fpq7 + fpq8 + fpq9 + fpq10 +fpq11 + fpq12 + fpq13 + fpq14 + fpq15 + fpq16 + fpq17 + fpq18 + fpq19 + fpq20)
  )

```

# Demographics
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
dt01 <- final_dataset %>%
  dplyr::select(`Which country are you from?`, `What discipline of global health based describes you:`, `What is you gender?`, `How many years of involvement in research do you have?`, `Which of the following best describes you?`, `What is your highest academic rank?`) %>%
  # mutate(gender = factor(gender, labels = c('Females', 'Males'))) %>%
  tbl_summary(by = `Which of the following best describes you?`, 
            missing = "no",
            # statistic = list(all_continuous() ~ "{mean} ({sd})")
            ) %>% 
  # add_p() %>%
  add_n() %>% 
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()

dt01
```


# Responsible research practices and fair research practices by the question which of the following best describes you?
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
dt02 <- final_dataset %>%
  dplyr::select(rpq1, rpq2, rpq3, rpq4, rpq5, rpq6, rpq7, rpq8, rpq9, rpq10, rpq11, rpq12, rpq13, rpq14, rpq15, rpq16, rpq17, rpq18, rpq19, rpq20, fpq1, fpq2, fpq3, fpq4, fpq5, fpq6, fpq7, fpq8, fpq9, fpq10, fpq11, fpq12, fpq13, fpq14, fpq15, fpq16, fpq17, fpq18, fpq19, fpq20, `responsible research Practices score`, `fair research practices score`, `Which of the following best describes you?`) %>%
  tbl_summary(by = `Which of the following best describes you?`, 
            missing = "no",
            type = list(c('rpq1', 'rpq2', 'rpq3', 'rpq4', 'rpq5', 'rpq6', 'rpq7', 'rpq8', 'rpq9', 'rpq10', 'rpq11', 'rpq12', 'rpq13', 'rpq14', 'rpq15', 'rpq16', 'rpq17', 'rpq18', 'rpq19', 'rpq20', 'fpq1', 'fpq2', 'fpq3', 'fpq4', 'fpq5', 'fpq6', 'fpq7', 'fpq8', 'fpq9', 'fpq10', 'fpq11', 'fpq12', 'fpq13', 'fpq14', 'fpq15', 'fpq16', 'fpq17', 'fpq18', 'fpq19', 'fpq20', 'responsible research Practices score', 'fair research practices score') ~ 'continuous'),
            statistic = list(c('rpq1', 'rpq2', 'rpq3', 'rpq4', 'rpq5', 'rpq6', 'rpq7', 'rpq8', 'rpq9', 'rpq10', 'rpq11', 'rpq12', 'rpq13', 'rpq14', 'rpq15', 'rpq16', 'rpq17', 'rpq18', 'rpq19', 'rpq20', 'fpq1', 'fpq2', 'fpq3', 'fpq4', 'fpq5', 'fpq6', 'fpq7', 'fpq8', 'fpq9', 'fpq10', 'fpq11', 'fpq12', 'fpq13', 'fpq14', 'fpq15', 'fpq16', 'fpq17', 'fpq18', 'fpq19', 'fpq20', 'responsible research Practices score', 'fair research practices score') ~ "{mean} ({sd})")
            ) %>% 
  # add_p() %>%
  add_n() %>% 
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()
dt02
```


# Responsible research practices and fair research practices by location (Global North or South)

In this analysis, I have removed those who chose the option prefer not to say
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
dt03 <- final_dataset %>%
  mutate(location = as.factor(case_when(
    `Which of the following best describes you?` == 'Researcher from the Global North' ~ 'Global North',
    `Which of the following best describes you?` == 'Researcher from the Global South' ~ 'Global South'#,
    # `Which of the following best describes you?` == '' ~ 'Global North',
  ))) %>%
  dplyr::select(rpq1, rpq2, rpq3, rpq4, rpq5, rpq6, rpq7, rpq8, rpq9, rpq10, rpq11, rpq12, rpq13, rpq14, rpq15, rpq16, rpq17, rpq18, rpq19, rpq20, fpq1, fpq2, fpq3, fpq4, fpq5, fpq6, fpq7, fpq8, fpq9, fpq10, fpq11, fpq12, fpq13, fpq14, fpq15, fpq16, fpq17, fpq18, fpq19, fpq20, `responsible research Practices score`, `fair research practices score`, location) %>%
  tbl_summary(by = location, 
            missing = "no",
            type = list(c('rpq1', 'rpq2', 'rpq3', 'rpq4', 'rpq5', 'rpq6', 'rpq7', 'rpq8', 'rpq9', 'rpq10', 'rpq11', 'rpq12', 'rpq13', 'rpq14', 'rpq15', 'rpq16', 'rpq17', 'rpq18', 'rpq19', 'rpq20', 'fpq1', 'fpq2', 'fpq3', 'fpq4', 'fpq5', 'fpq6', 'fpq7', 'fpq8', 'fpq9', 'fpq10', 'fpq11', 'fpq12', 'fpq13', 'fpq14', 'fpq15', 'fpq16', 'fpq17', 'fpq18', 'fpq19', 'fpq20', 'responsible research Practices score', 'fair research practices score',) ~ 'continuous'),
            statistic = list(c('rpq1', 'rpq2', 'rpq3', 'rpq4', 'rpq5', 'rpq6', 'rpq7', 'rpq8', 'rpq9', 'rpq10', 'rpq11', 'rpq12', 'rpq13', 'rpq14', 'rpq15', 'rpq16', 'rpq17', 'rpq18', 'rpq19', 'rpq20', 'fpq1', 'fpq2', 'fpq3', 'fpq4', 'fpq5', 'fpq6', 'fpq7', 'fpq8', 'fpq9', 'fpq10', 'fpq11', 'fpq12', 'fpq13', 'fpq14', 'fpq15', 'fpq16', 'fpq17', 'fpq18', 'fpq19', 'fpq20', 'responsible research Practices score', 'fair research practices score') ~ "{mean} ({sd})")
            ) %>% 
  add_p() %>%
  add_n() %>% 
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()
dt03
```


<!-- # Responsible research practices -->
<!-- ```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'} -->

<!-- ``` -->