---
title: "Addison's disease associated with advanced HIV may explain the high mortality"
author: "Dr Joseph B Sempa"
date: "`r Sys.Date()`"
output:
  word_document:
    fig_caption: yes
    toc: yes
  pdf_document:
    fig_caption: yes
    toc: yes
  html_document:
    fig_caption: yes
    toc: yes
  html_notebook:
    toc: yes
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(results = 'asis')
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(magrittr)
library(knitr)
# library(kableExtra)
library(tinytex)
library(gmodels)
library(readxl)
# library(MASS)
library(gtsummary)
library(caret)
library(leaps)
library(MASS)
library(predtools)
library(randomForest)
library(mice)
# library(psfmi)
library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(survminer)
library(ggpubr)
library(rstatix)
```


```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
final_dataset <- read_excel("hypo_alldata_wide_labels - 554.xls") %>%
  mutate(addisons_disease = ifelse(as.numeric(`Random cortisol result`) < 500, 1, 0),
         # addisons_status = ifelse(as.numeric(`Random cortisol result`) < 200, "probable", ifelse(as.numeric(`Random cortisol result`) >=200 & as.numeric(`Random cortisol result`) < 500, 'Suspects')),
         # addisons_disease = ifelse(addisons_disease == 1 & as.numeric(``) < 500), 1, 0),
         PAI = ifelse(as.numeric(`Random cortisol result`) < 500 & as.numeric(`Synacthen: 30 minute cortisol result`) < 500 & (as.numeric(`ACTH result`) >= 64.7 & !is.na(`ACTH result`)), 1, 0),
         SAI = ifelse(as.numeric(`Random cortisol result`) < 500 & as.numeric(`Synacthen: 30 minute cortisol result`) < 500 & (as.numeric(`ACTH result`) < 64.7), 1, 0),
         total_AI = ifelse(as.numeric(`Random cortisol result`) < 500 & (PAI == 1 | SAI == 1), 1, 
                           ifelse(as.numeric(`Random cortisol result`) < 500 & (PAI != 1 & SAI != 1), 0, NA)),
         addisons_disease  = ifelse(is.na(total_AI), 0, total_AI),
         addisons_disease = ifelse(UIN...1 %in% c(392, 435, 478, 488, 496, 500), 1, addisons_disease)
           ) %>%
  mutate(AI = ifelse(PAI == 1, 'PAI', 
                     ifelse(SAI == 1, 'SAI', ''))) %>%
  mutate(AI = ifelse(UIN...1 %in% c(435, 478, 488, 496), 'SAI',
                                   ifelse(UIN...1 %in% c(392, 500), 'PAI', AI)),
         `Adrenal insufficiency` = ifelse(!is.na(addisons_disease), addisons_disease, 0)#,
         # `Loss of axillary and pubic hair, if female` = ifelse(`Loss of axillary and pubic hair, if female` == 'Not applicable', '', `Loss of axillary and pubic hair, if female`)
         ) %>%
  mutate(`Increased pigmentation of the skin` = as.logical(ifelse(`Increased pigmentation of the skin` == 'Yes', 1, 0)),
         `Loss of consciousness` = as.logical(ifelse(`Loss of consciousness` == 'Yes', 1, 0)),
         `Hypoglycaemia` = as.logical(ifelse(`Hypoglycaemia` == 'Yes', 1, 0)),
         Dizziness = as.logical(ifelse(Dizziness == 'Yes', 1, 0)),
         Shock = as.logical(ifelse(Shock == 'Yes', 1, 0)),
         `Presence of anaemia` = as.logical(ifelse(`Presence of anaemia` == 'Yes', 1, 0)),
         Hypotension = as.logical(ifelse(Hypotension == 'Yes', 1, 0)),
         Weakness = as.logical(ifelse(Weakness == 'Yes', 1, 0)),
         Tiredness = as.logical(ifelse(Tiredness == 'Yes', 1, 0)),
         `Poor appetite` = as.logical(ifelse(`Poor appetite` == 'Yes', 1, 0)),
         `Weight loss` = as.logical(ifelse(`Weight loss` == 'Yes', 1, 0)),
         Nausea = as.logical(ifelse(Nausea == 'Yes', 1, 0)),
         Vomiting = as.logical(ifelse(Vomiting == 'Yes', 1, 0)),
         `Liking for salt` = as.logical(ifelse(`Liking for salt` == 'Yes', 1, 0)),
         Diarrhoea = as.logical(ifelse(Diarrhoea == 'Yes', 1, 0)),
         Anorexia = as.logical(ifelse(Anorexia == 'Yes', 1, 0)),
         `Loss of axillary and pubic hair, if female` = ifelse(`Loss of axillary and pubic hair, if female` == 'NA', 'No', `Loss of axillary and pubic hair, if female`),
         `Any postural drop in blood pressure` = as.logical(ifelse(`Any postural drop in blood pressure` == 'Yes', 1, 0)),
         incremental_cortisol = (`Synacthen: 30 minute cortisol result` - `Synacthen: 0 minute cortisol result`)
         ) %>%
  mutate(incremental_cortisol = ifelse(incremental_cortisol<0, NA, incremental_cortisol)) #%>%
#   dplyr::select(id = UIN...1, `Hospital folder number`, `Primary medical conditions (1)`, `Primary medical conditions (2)`, `Primary medical conditions (3)`, `Primary medical conditions (4)`, `Co-existing medical conditions (2)`, `Other, specify...67`,
#                 `Opportunistic infection  (choice=Tuberculosis)`, `Opportunistic infection  (choice=Cryptococcus neoformans)`,
# `Opportunistic infection  (choice=Toxoplasmosis)`, `Opportunistic infection  (choice=Mycobacterium avium-intracellulare)`, `Opportunistic infection  (choice=Kaposis sarcoma)`, `Opportunistic infection  (choice=Cytomegalovirus)`,`Opportunistic infection  (choice=Other)`) 
# write.csv(final_dataset, 'opportunistic infections_554.csv')
# dt01 <- read_csv("opportunistic infections_554.csv") %>%
#   filter(!(`Hospital folder number` %in% read_excel("hypo_alldata_wide_labels 549.xlsx")$`Hospital folder number`))
# write.csv(dt01, 'opportunistic infections_updated_549_to_554.csv')
dat <- final_dataset %>%
dplyr::select(`Hospital folder number`,`Random cortisol result`, `ACTH sample drawn`, `ACTH result`, `Synacthen: 0 minute cortisol result`, `Synacthen: 30 minute cortisol result`, addisons_disease)
write.csv(dat, 'outcome_dat.csv')
final_dataset <- final_dataset %>%
  left_join(bind_rows(
  read_excel("Updated OI's  05 March 2024.xlsx"), 
  read_excel("opportunistic infections_additional_patients +OI_updated.xlsx"),
  read_excel("opportunistic infections_additional_patients +OI - 554.xlsx")
) %>%
  mutate(Tuberculosis = as.logical(`Opportunistic infection  (choice=Tuberculosis)`), 
         `Cryptococcus neoformans` = as.logical(`Opportunistic infection  (choice=Cryptococcus neoformans)`), 
         Pneumonia = as.logical(`Opportunistic infection  (choice=Pneumonia)`),
         `Staph aureus` = as.logical(`Opportunistic infection  (choice=Staph aureus)`), 
         `Kaposis sarcoma` = as.logical(`Opportunistic infection  (choice=Kaposis sarcoma)`),
         Cytomegalovirus = as.logical(`Opportunistic infection  (choice=Cytomegalovirus)`), 
         HSV = as.logical(`Opportunistic infection  (choice=HSV)`), 
         HepB = as.logical(`Opportunistic infection  (choice=HepB)`),
         Candida = as.logical(`Opportunistic infection  (choice=Candida)`),
         Other = as.logical(`Opportunistic infection  (choice=Other)`),
         `GE/c diff`  = as.logical(`Opportunistic infection  (choice=GE / C diff)`), 
         `Parvo B19` = as.logical(`Opportunistic infection  (choice=Parvo B19)`),
         `Syphilis` = as.logical(`Opportunistic infection  (choice=Syphilis)`),
         `B menigitis` = as.logical(`Opportunistic infection  (choice=B menigitis)`), 
         `UTI / Leptospirosis` = as.logical(`Opportunistic infection  (choice=UTI / Leptospirosis)`), 
         PCP = as.logical(`Opportunistic infection  (choice=PCP)`), 
         `COVID-19` = as.logical(`Opportunistic infection  (choice=covid)`),
         `Neurocysticercosis` = as.logical(`Opportunistic infection  (choice=Neurocysticercosis)`)) %>%
  dplyr::select(`Hospital folder number`, Tuberculosis,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, Other, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`) %>% 
  replace(is.na(.), 0), by = 'Hospital folder number') %>%
  left_join(read_delim("opportunistic infections_554 - TB.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE) %>%
              dplyr::select(`Hospital folder number`, PTB, EPTB), by = 'Hospital folder number') %>%
  mutate(`White cell count` = as.numeric(`White cell count`),
         `Lymphocyte count` = as.numeric(`Lymphocyte count`),
         Neutrophils = as.numeric(Neutrophils))
# cod_oi <- read_excel("hypo_alldata_wide_labels_cod_oi.xls") %>%
#   dplyr::select(`Hospital folder number`, `If deceased, cause of death`)
# write.csv(final_dataset %>% 
#             # mutate(total_AI = ifelse(is.na(total_AI), 0, total_AI)) %>%
#             relocate(addisons_disease, .after = `Hospital folder number`), "Full_528_dataset.csv")
# write.csv(final_dataset %>% 
#             # mutate(total_AI = ifelse(is.na(total_AI), 0, total_AI)) %>%
#             relocate(addisons_disease, .after = `Hospital folder number`) %>%
#             dplyr::select(`Hospital folder number`, addisons_disease, `Random cortisol result`, 
#                           `Synacthen: 0 minute cortisol result`, `ACTH result`, 
#                           `Synacthen: 30 minute cortisol result`), "stimulation_test_dataset.csv")
# 
# dt02 <- final_dataset %>%
#   filter(!(`Hospital folder number` %in% read_csv("opportunistic infections.csv")$`Hospital folder number`)) %>%
#   dplyr::select(id = `Hospital folder number`, `Concomitant therapy (1)`, `Concomitant therapy (2)`, `Concomitant therapy (3)`, `Concomitant therapy (4)`, `Concomitant therapy (5)`, `Concomitant therapy (6)`, `Concomitant therapy (7)`, `Concomitant therapy (8)`, `Concomitant therapy (9)`, `Concomitant therapy (10)`) %>%
#   pivot_longer(cols=c(`Concomitant therapy (1)`, `Concomitant therapy (2)`, `Concomitant therapy (3)`, `Concomitant therapy (4)`, `Concomitant therapy (5)`, `Concomitant therapy (6)`, `Concomitant therapy (7)`, `Concomitant therapy (8)`, `Concomitant therapy (9)`, `Concomitant therapy (10)`),
#                     names_to='drug',
#                     values_to='drug2') %>%
#   filter(drug2 != 'NA')
# write.csv(dt02, 'list of drugs_additional_patients.csv')
dt03 <- bind_rows(
  read_delim("list of drugs - updated 23 April24 TB & Fungal .csv",
    delim = ";", escape_double = FALSE, trim_ws = TRUE
  ) %>%
    dplyr::select(id, ART, tb, kidney, fungal, rifampicin, fluconazole, opiates),
  read_delim("list of drugs_additional_patients + CKD, TB & Fungal.csv",
    delim = ";", escape_double = FALSE, trim_ws = TRUE
  )
) %>%
  dplyr::select(id, ART, tb = TB, kidney, fungal = Fungal, rifampicin, fluconazole, opiates) %>%
  group_by(id) %>%
  mutate(
    `ART exposure` = max(ifelse(is.na(ART), 0, ART), na.rm = T),
    `Kidney medication` = max(ifelse(is.na(kidney), 0, kidney), na.rm = T),
    `TB medication` = max(ifelse(is.na(tb), 0, tb), na.rm = T),
    `Fungal medication` = max(ifelse(is.na(fungal), 0, fungal), na.rm = T),
    `rifampicin` = max(ifelse(is.na(rifampicin), 0, rifampicin), na.rm = T),
    `fluconazole` = max(ifelse(is.na(fluconazole), 0, fluconazole), na.rm = T),
    `opiates` = max(ifelse(is.na(opiates), 0, opiates), na.rm = T)
  ) %>%
  ungroup() %>%
  distinct(id, .keep_all = T) %>%
  dplyr::select(id, `ART exposure`, `Kidney medication`, `TB medication`, `Fungal medication`,
    Rifampicin = `rifampicin`, Fluconazole = `fluconazole`, `Opiates` = `opiates`
  )

final_dataset <- final_dataset %>%
  # dplyr::select(id = `Hospital folder number`, `CD4 count` = `Total CD4 count...10`) %>%
  left_join(dt03 %>%
    mutate(`Hospital folder number` = id), by = "Hospital folder number") %>%
  mutate(
    `ART exposure` = as.factor(ifelse(is.na(`ART exposure`), "No",
      ifelse(`ART exposure` == 1, "Yes",
        ifelse(`ART exposure` == 0, "No", `ART exposure`)
      )
    )),
    `Kidney medication` = as.factor(ifelse(is.na(`Kidney medication`), "No",
      ifelse(`Kidney medication` == 1, "Yes",
        ifelse(`Kidney medication` == 0, "No", `Kidney medication`)
      )
    )),
    `TB medication` = as.factor(ifelse(is.na(`TB medication`), "No",
      ifelse(`TB medication` == 1, "Yes",
        ifelse(`TB medication` == 0, "No", `TB medication`)
      )
    )),
    `Fungal medication` = as.factor(ifelse(is.na(`Fungal medication`), "No",
      ifelse(`Fungal medication` == 1, "Yes",
        ifelse(`Fungal medication` == 0, "No", `Fungal medication`)
      )
    )),
    Rifampicin = as.factor(ifelse(is.na(Rifampicin), "No",
      ifelse(Rifampicin == 1, "Yes",
        ifelse(Rifampicin == 0, "No", Rifampicin)
      )
    )),
    Fluconazole = as.factor(ifelse(is.na(Fluconazole), "No",
      ifelse(Fluconazole == 1, "Yes",
        ifelse(Fluconazole == 0, "No", Fluconazole)
      )
    )),
    Opiates = as.factor(ifelse(is.na(Opiates), "No",
      ifelse(Opiates == 1, "Yes",
        ifelse(Opiates == 0, "No", Opiates)
      )
    ))
  ) # %>%
  # mutate(`CD4 count` = as.numeric(`CD4 count`))
```

# Baseline table
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# `Primary medical conditions (1)`, `Primary medical conditions (2)`, `Primary medical conditions (3)`, `Primary medical conditions (4)`, Co-existing medical conditions (2), Other, specify...67,
table_1 <- final_dataset %>%
  mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
         `White cell count` = as.numeric(`White cell count`),
         `Lymphocyte count` = as.numeric(`Lymphocyte count`),
         Neutrophils = as.numeric(Neutrophils),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.logical(ifelse(addisons_disease ==1, 'yes', ifelse(addisons_disease ==0, 'no', ''))),
         Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity))
         ) %>%
  dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Weight loss`, `Viral load, log10 copies/ml`= `log10 viral load`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Total CD4 count`, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates) %>%
tbl_summary(#table_1,
            missing = "no",
            digits = list(all_categorical() ~ c(0, 1),
                          all_continuous() ~ c(1, 1))#,
            # label = list('Gender, n(%)', 'Ethnicity, n(%)')
            ) %>%
  add_n() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels() %>%
  modify_caption("**Baseline table**")
table_1

```

# Table 1
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# table_1 <- final_dataset %>%
#   mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
#          `Age at enrolment` = as.numeric(`Age at enrolment`),
#          `Duration of current illness` = as.numeric(`Duration of current illness`),
#          `Total CD4 count` = as.numeric(`Total CD4 count...10`),
#          HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
#          `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
#          `Addisons disease`  = as.factor(ifelse(addisons_disease ==1, 'yes', ifelse(addisons_disease ==0, 'no', ''))),
#          Sodium = as.numeric(Sodium),
#          Potassium = as.numeric(Potassium),
#          Haemoglobin = as.numeric(Haemoglobin), 
#          `White cell count` = as.numeric(`White cell count`), 
#          `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
#          Neutrophils = as.numeric(Neutrophils),
#          Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity))
#          ) %>%
#   mutate(
#     # `Tuberculosis` = as.factor(`Opportunistic infection  (choice=Tuberculosis)`),
#     # `Cryptococcus neoformans` = as.factor(`Opportunistic infection  (choice=Cryptococcus neoformans)`),
#     `Toxoplasmosis` = as.logical(`Opportunistic infection  (choice=Toxoplasmosis)`)#,
#     # `Mycobacterium avium-intracellulare` = as.factor(`Opportunistic infection  (choice=Mycobacterium avium-intracellulare)`),
#     # `Kaposis sarcoma` = as.factor(`Opportunistic infection  (choice=Kaposis sarcoma)`),
#     # `Cytomegalovirus` = as.factor(`Opportunistic infection  (choice=Cytomegalovirus)`),
#     # `Other` = as.factor(`Opportunistic infection  (choice=Other)`)
#   ) %>%
#   filter(Gender != 'Unknown') %>%
#   dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Weight loss`, `log10 viral load`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Total CD4 count`, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `ART exposure`, `Kidney medication`Rifampicin, Fluconazole, Opiates) %>% #`Opportunistic infection present`, 
# tbl_summary(#table_1,
#             missing = "no",
#             by = `Gender, n(%)`,
#             # statistic = list(all_continuous() ~ "{mean} ({sd})"),
#             digits = list(all_categorical() ~ c(0, 1),
#                           all_continuous() ~ c(1, 1))#,
#             # label = list(`Total CD4 count...10` ~ 'Total CD4 count')
#             ) %>%
#   add_p() %>%
#   # add_n() %>%
#   # add_overall() %>%
#   modify_header(label = "Variable") %>% # update the column header
#   bold_labels()  %>%
#   modify_caption('Table 1: gender')
# table_1
# 
table_1_2 <- final_dataset %>%
  mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(ifelse(addisons_disease ==1, 'yes', ifelse(addisons_disease ==0, 'no', ''))),
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin),
         `White cell count` = as.numeric(`White cell count`),
         `Lymphocyte count` = as.numeric(`Lymphocyte count`),
         Neutrophils = as.numeric(Neutrophils)#,
         # Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity))
         ) %>%
  mutate(
    # `Age at enrolment` = cut(as.numeric(`Age at enrolment`), breaks = c(-Inf, 30, 37, Inf)),
    # `Tuberculosis` = as.factor(`Opportunistic infection  (choice=Tuberculosis)`),
    # `Cryptococcus neoformans` = as.factor(`Opportunistic infection  (choice=Cryptococcus neoformans)`),
    `Toxoplasmosis` = as.logical(`Opportunistic infection  (choice=Toxoplasmosis)`)#,
    # `Mycobacterium avium-intracellulare` = as.factor(`Opportunistic infection  (choice=Mycobacterium avium-intracellulare)`),
    # `Kaposis sarcoma` = as.factor(`Opportunistic infection  (choice=Kaposis sarcoma)`),
    # `Cytomegalovirus` = as.factor(`Opportunistic infection  (choice=Cytomegalovirus)`),
    # `Other` = as.factor(`Opportunistic infection  (choice=Other)`)
  ) %>%
  filter(Gender != 'Unknown') %>%
  dplyr::select(`Age at enrolment`, `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Weight loss`, `log10 viral load`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Total CD4 count`, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates) %>% #`Opportunistic infection present`,
tbl_summary(#table_1,
            missing = "no",
            by = `ART exposure`,
            # statistic = list(all_continuous() ~ "{mean} ({sd})"),
            digits = list(all_categorical() ~ c(0, 1),
                          all_continuous() ~ c(1, 1))#,
            # label = list(`Total CD4 count...10` ~ 'Total CD4 count')
            ) %>%
  add_p() %>%
  # add_n() %>%
  # add_overall() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels() %>%
  modify_caption('Table 2: ARV status')
table_1_2

pai <- unique(final_dataset$UIN...1[final_dataset$AI == 'PAI'])
sai <- unique(final_dataset$UIN...1[final_dataset$AI == 'SAI'])
no_AI <- unique(final_dataset$UIN...1[final_dataset$addisons_disease == 0])

dt02 <- final_dataset %>%
   dplyr::select(id = UIN...1, AI, `ART exposure`, `Kidney medication`, `Concomitant therapy (1)`, `Concomitant therapy (2)`, `Concomitant therapy (3)`, `Concomitant therapy (4)`, `Concomitant therapy (5)`, `Concomitant therapy (6)`, `Concomitant therapy (7)`, `Concomitant therapy (8)`, `Concomitant therapy (9)`, `Concomitant therapy (10)`) %>%
   pivot_longer(
     cols = c(`Concomitant therapy (1)`, `Concomitant therapy (2)`, `Concomitant therapy (3)`, `Concomitant therapy (4)`, `Concomitant therapy (5)`, `Concomitant therapy (6)`, `Concomitant therapy (7)`, `Concomitant therapy (8)`, `Concomitant therapy (9)`, `Concomitant therapy (10)`),
     names_to = "drug",
     values_to = "drug2"
   ) %>%
   filter(drug2 != "NA") %>%
   mutate(AI = ifelse(id %in% pai & !is.na(pai), "PAI",
     ifelse(id %in% sai & !is.na(sai), "SAI",
       ifelse(id %in% no_AI & !is.na(sai), "no AI", "")
     )
   )) %>%
  mutate(AI_coded = ifelse(AI == 'no AI', 1,
                           ifelse(AI == 'PAI', 2,
                                  ifelse(AI == 'SAI', 3, NA)))) %>%
  group_by(id) %>%
  mutate(AIcode_filled = min(AI_coded, na.rm = T)) %>%
  ungroup() %>%
  filter(`ART exposure` == 'Yes' | `Kidney medication` == 'Yes') %>%
  mutate(AI = ifelse(AIcode_filled == 1, 'no AI',
                     ifelse(AIcode_filled == 2, 'PAI',
                            ifelse(AIcode_filled == 3, 'SAI', '')))) %>%
  dplyr::select(AI, drug2, `ART exposure`, `Kidney medication`)

# dt03 <- dt02 %>%
  

```

# Table 1.2
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
table_12 <- final_dataset %>%
  mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(ifelse(addisons_disease ==1, 'yes', ifelse(addisons_disease ==0, 'no', ''))),
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin),
         `White cell count` = as.numeric(`White cell count`),
         `Lymphocyte count` = as.numeric(`Lymphocyte count`),
         Neutrophils = as.numeric(Neutrophils),
         Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity))
         ) %>%
  mutate(
    # `Tuberculosis` = as.factor(`Opportunistic infection  (choice=Tuberculosis)`),
    # `Cryptococcus neoformans` = as.factor(`Opportunistic infection  (choice=Cryptococcus neoformans)`),
    `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
    # `Mycobacterium avium-intracellulare` = as.factor(`Opportunistic infection  (choice=Mycobacterium avium-intracellulare)`),
    # `Kaposis sarcoma` = as.factor(`Opportunistic infection  (choice=Kaposis sarcoma)`),
    # `Cytomegalovirus` = as.factor(`Opportunistic infection  (choice=Cytomegalovirus)`),
    # `Other` = as.factor(`Opportunistic infection  (choice=Other)`)
  ) %>%
  mutate(`CD4 counts` = case_when(
    as.numeric(`Total CD4 count`) <= 33 ~ '0 - 33',
    as.numeric(`Total CD4 count`) >33 & as.numeric(`Total CD4 count` <=66) ~ '34 - 66',
    as.numeric(`Total CD4 count`) > 66 & as.numeric(`Total CD4 count` <= 100) ~ '67 - 100'
  )) %>%
  dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, 
                `Gender, n(%)` = `Gender`, 
`Duration of current illness, median (IQR) (days)` = `Duration of current illness`, 
`Weight loss`, `log10 viral load`, Tuberculosis, Pneumonia, Candida, `Cryptococcus neoformans`, 
`GE/c diff`, HepB, `Syphilis`, `Kaposis sarcoma`, `UTI / Leptospirosis`, 
PCP, HSV, `B menigitis`, `White cell count X109` = `White cell count`, 
`Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `ART exposure`, 
`TB medication`, `Fungal medication`, `Kidney medication`, Rifampicin, 
Fluconazole, Opiates, `Ethnicity, n(%)` = Ethnicity, Tuberculosis, `Staph aureus`, 
Cytomegalovirus, `Parvo B19`, PTB, EPTB, `COVID-19`, `Neurocysticercosis`, `CD4 counts`
    ) %>%# ,
tbl_summary(#table_1,
            missing = "no",
            by = `CD4 counts`,
            # statistic = list(all_continuous() ~ "{mean} ({sd})"),
            digits = list(all_categorical() ~ c(0, 1),
                          all_continuous() ~ c(1, 1))#,
            # label = list(`Total CD4 count...10` ~ 'Total CD4 count')
            ) %>%
  add_p() %>%
  # add_n() %>%
  add_overall() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()  %>%
  modify_caption('Table 1 (artcile): Patient presentation by CD4 count category')

table_12

```

```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}

dt02 <- bind_rows(final_dataset %>%
  mutate(`AI status` = ifelse(addisons_disease==1, 'Adrenal insufficiency', 'No Adrenal insufficiency'),
         Group = as.factor('Random cortisol')) %>%
  dplyr::select(id = `Hospital folder number`, `AI status`, Group, result = `Random cortisol result`),
  final_dataset %>%
  mutate(`AI status` = ifelse(addisons_disease==1, 'Adrenal insufficiency', 'No Adrenal insufficiency'),
         Group = as.factor('Basal cortisol')
         ) %>%
  dplyr::select(id = `Hospital folder number`, `AI status`, Group, result = `Synacthen: 0 minute cortisol result`), 
  final_dataset %>%
  mutate(`AI status` = ifelse(addisons_disease==1, 'Adrenal insufficiency', 'No Adrenal insufficiency'),
         Group = as.factor('Stimulated cortisol')
         ) %>%
  dplyr::select(id = `Hospital folder number`, `AI status`, Group, result = `Synacthen: 30 minute cortisol result`), 
  final_dataset %>%
  mutate(`AI status` = ifelse(addisons_disease==1, 'Adrenal insufficiency', 'No Adrenal insufficiency'),
         Group = as.factor('ACTH')) %>%
  dplyr::select(id = `Hospital folder number`, `AI status`, Group, result = `ACTH result`)
  ) %>%
  mutate(result = as.numeric(result))

dt02_1 <- dt02 %>%
   group_by(Group) %>%
   summarise(med_ian = median(result, na.rm = T),
             p25 = quantile(result, 0.25, na.rm = T),
             p75 = quantile(result, 0.75, na.rm = T),
             min = min(result, na.rm = T),
             max = max(result, na.rm = T))
View(dt02_1)
write.csv(dt02_1, 'Cortisol_measurements.csv')

stat.test <- dt02 %>%
  filter(!(as.character(Group) == 'ACTH')) %>%
  mutate(AI_status = as.factor(`AI status`)) %>%
  group_by(Group) %>%
  t_test(result ~ AI_status) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") %>%
  add_xy_position(x = "Group", dodge = 0.8) %>%
  mutate(p.adj_1 = ifelse(p.adj <0.0001, "<0.0001", '0.768'))
stat.test

box_plot_1 <- ggboxplot(
  dt02 %>%
    filter(!(as.character(Group) == 'ACTH')), x = 'Group', y = 'result',
  fill = "AI status", palette = c("#00AFBB", "#E7B800"),
  ylab = 'Serum cortisol concentration (nmol/L)',
  xlab = 'Laboratory test'
) +
  stat_pvalue_manual(
    stat.test,  label = "{p.adj_1}{p.adj.signif}", 
    tip.length = 0, hide.ns = FALSE
  )+ 
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  theme(
    text = element_text(size = 20),
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    panel.background = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(0, 0, 0, 0), "null")#,
    # axis.text.x = element_text(angle = 60, hjust = 1)
  )

jpeg('boxplot_1.png', units = "in", width = 10, height = 9, res = 300)

box_plot_1

dev.off()

dt06 <- bind_rows(final_dataset %>%
                    mutate(Group = as.factor('ART exposure')) %>%
                    dplyr::select(id = `Hospital folder number`, Group,`CD4 count`= `Total CD4 count...10`, treatment = `ART exposure`),
                  final_dataset %>%
                    mutate(Group = as.factor('Kidney medication')) %>%
                    dplyr::select(id = `Hospital folder number`, Group,`CD4 count`= `Total CD4 count...10`, treatment = `Kidney medication`)
  
) %>%
  mutate(`CD4 count` = as.numeric(`CD4 count`))
stat.test <- dt06 %>%
  # mutate(AI_status = as.factor(`AI status`)) %>%
  group_by(Group) %>%
  t_test(`CD4 count` ~ treatment) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") %>%
  add_xy_position(x = "Group", dodge = 0.8)
stat.test

box_plot_2 <- ggboxplot(
  dt06, x = 'Group', y = 'CD4 count',
  fill = "treatment", palette = c("#00AFBB", "#E7B800")
  ) +
  stat_pvalue_manual(
  stat.test,  label = "{p.adj}{p.adj.signif}", 
  tip.length = 0, hide.ns = FALSE
  )+
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  theme(
    text = element_text(size = 20),
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    panel.background = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(0, 0, 0, 0), "null")#,
    # axis.text.x = element_text(angle = 60, hjust = 1)
  )

jpeg('box_plot_2.png', units = "in", width = 8, height = 9, res = 300)

box_plot_2

dev.off()

dt07 <- bind_rows(final_dataset %>%
                    # filter(`ART exposure` == 'Yes') %>%
  mutate(diagnosis = ifelse(AI == 'PAI', 'PAI', 
                            ifelse(AI == 'SAI', 'SAI', 
                                   ifelse(addisons_disease == 0, 'No AI', '')))) %>%
  mutate(diagnosis = ifelse(is.na(diagnosis), 'No AI', diagnosis),
         value = ifelse(`ART exposure` == 'Yes', 1,0),
         medication = 'ART') %>%
    dplyr::select(diagnosis, value, medication),
  final_dataset %>%
    # filter(`Kidney medication` == 'Yes') %>%
  mutate(diagnosis = ifelse(AI == 'PAI', 'PAI', 
                            ifelse(AI == 'SAI', 'SAI', 
                                   ifelse(addisons_disease == 0, 'No AI', '')))) %>%
  mutate(diagnosis = ifelse(is.na(diagnosis), 'No AI', diagnosis),
         value = ifelse(`Kidney medication` == 'Yes', 1,0),
         medication = 'Kidney') %>%
    dplyr::select(diagnosis, value, medication),
  final_dataset %>%
    # filter(`TB medication` == 'Yes') %>%
  mutate(diagnosis = ifelse(AI == 'PAI', 'PAI', 
                            ifelse(AI == 'SAI', 'SAI', 
                                   ifelse(addisons_disease == 0, 'No AI', '')))) %>%
  mutate(diagnosis = ifelse(is.na(diagnosis), 'No AI', diagnosis),
         value = ifelse(`TB medication` == 'Yes', 1,0),
         medication = 'TB') %>%
    dplyr::select(diagnosis, value, medication),
  final_dataset %>%
    # filter(`Fungal medication` == 'Yes') %>%
  mutate(diagnosis = ifelse(AI == 'PAI', 'PAI', 
                            ifelse(AI == 'SAI', 'SAI', 
                                   ifelse(addisons_disease == 0, 'No AI', '')))) %>%
  mutate(diagnosis = ifelse(is.na(diagnosis), 'No AI', diagnosis),
         value = ifelse(`Fungal medication` == 'Yes', 1,0),
         medication = 'Fungal') %>%
    dplyr::select(diagnosis, value, medication) ) 
dt08 <- final_dataset %>%
    # filter(`Fungal medication` == 'Yes') %>%
  mutate(diagnosis = ifelse(AI == 'PAI', 'PAI', 
                            ifelse(AI == 'SAI', 'SAI', 
                                   ifelse(addisons_disease == 0, 'No AI', '')))) %>%
  mutate(diagnosis = ifelse(is.na(diagnosis), 'No AI', diagnosis)) %>%
  dplyr::select(diagnosis, `ART exposure`, `Kidney medication`, `TB medication`, `Fungal medication`) %>%
  mutate(diagnosis = fct_relevel(diagnosis, 'SAI', after = 1)) %>%
  tbl_summary(#table_1,
            missing = "no",
            by = diagnosis,
            # statistic = list(all_continuous() ~ "{mean} ({sd})"),
            digits = list(all_categorical() ~ c(0, 1))#,
            # label = list(`Total CD4 count...10` ~ 'Total CD4 count')
            ) %>%
  add_p() %>%
  # add_n() %>%
  add_overall() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()  %>%
  modify_caption('Table 3.1: addisons disease and medication')

dt08

dt09 <- dt07 %>%
  group_by(diagnosis, medication) %>%
  summarise(Total = sum(value)) %>%
  mutate(diagnosis = factor(diagnosis, level = c('No AI', 'SAI', 'PAI'))) %>%
  ggplot(aes(fill=medication, y=Total, x= diagnosis)) + 
    geom_bar(position="dodge", stat="identity") +
  theme(
    text = element_text(size = 20),
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    panel.background = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(0, 0, 0, 0), "null")#,
    # axis.text.x = element_text(angle = 60, hjust = 1)
  )

dt09
```

# Table 2: comparing Addisons status with other variables
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
fisher.test.simulate.p.values <- function(data, variable, by, ...) {
  result <- list()
  test_results <- stats::fisher.test(data[[variable]], data[[by]], simulate.p.value = TRUE)
  result$p <- test_results$p.value
  result$test <- test_results$method
  result
}
table_2 <- final_dataset %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(ifelse(addisons_disease ==1, 'AI', 'no-AI')),#ifelse(addisons_disease ==0, 
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin), 
         `White cell count` = as.numeric(`White cell count`), 
         `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
         Neutrophils = as.numeric(Neutrophils),
         `Random cortisol result` = as.numeric(`Random cortisol result`), 
    `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
    `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
    `ACTH result` = as.numeric(`ACTH result`), 
    `BP (systolic)` = as.numeric(`BP (systolic)`), 
    `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
    `Heart rate` = as.numeric(`Heart rate`),
    Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
    mortality = as.factor(ifelse(`3 followup_patientstatus` == 'Deceased --> EXIT form' | `6 followup_patientstatus` == 'Deceased --> EXIT form' | `12 followup_patientstatus` == 'Deceased --> EXIT form' | `Point of exit from study` == "Deceased", 'yes', 'no'))
  ) %>%
  # filter(AI != "") %>%
  dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, 	
`Gender, n(%)` = `Gender`, 	
`Duration of current illness, median (IQR) (days)` = `Duration of current illness`, 	
`Weight loss`, `Viral load (log10 Copies/mL)` = `log10 viral load`, 	
PTB, EPTB, `Cryptococcus neoformans`, Pneumonia, HepB, 	Candida, `Kaposis sarcoma`, 	
HSV, `GE/c diff`, `Total CD4 count`, `White cell count X109` = `White cell count`, 
`Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, 
`Sodium mmol/L` = Sodium, `Potassium mmol/L` = Potassium, 
`Haemoglobin g/dL` = Haemoglobin, `BP (systolic)`, `BP (diastolic)`, 
`Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, 	
`Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, 
Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, 
`Loss of axillary and pubic hair, if female`, 
`Any postural drop in blood pressure`, `Presence of anaemia`, mortality, 
Rifampicin, Fluconazole, Opiates, `ART exposure`, `Kidney medication`, 
`Kidney medication`, `Addisons disease`, `Ethnicity, n(%)` = Ethnicity, 
Tuberculosis, `Staph aureus`, Cytomegalovirus, `Parvo B19`, `Syphilis`, 
`B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`) %>%
  mutate(`Addisons disease` = forcats::fct_rev(`Addisons disease`)) %>%
  tbl_summary( # table_1,
    missing = "no",
    by = `Addisons disease`,
    type = list(c("Duration of current illness, median (IQR) (days)", #"Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH",
                  "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", "Age at enrolment, median (IQR) (years)", "Viral load (log10 Copies/mL)", "Total CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109", "Neutrophils") ~ "continuous"),#
          statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
    digits = list(all_categorical() ~ c(0, 1),
                  all_continuous() ~ c(1, 1))#,
    # label = list(`Total CD4 count...10` ~ "Total CD4 count")
  ) %>%
  add_p() %>%
  # add_n() %>%
  # add_overall() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()  %>%
  modify_caption('Table 2 (article): Should compare Total AI with Non-AI patients')
  
 table_2

table_2_1 <- final_dataset %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(`log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(ifelse(addisons_disease ==1, 'AI', 'no-AI')),#ifelse(addisons_disease ==0, 
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin), 
         `White cell count` = as.numeric(`White cell count`), 
         `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
         Neutrophils = as.numeric(Neutrophils),
         `Random cortisol result` = as.numeric(`Random cortisol result`), 
    `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
    `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
    `ACTH result` = as.numeric(`ACTH result`), 
    `BP (systolic)` = as.numeric(`BP (systolic)`), 
    `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
    `Heart rate` = as.numeric(`Heart rate`),
    Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
    mortality = as.factor(ifelse(`3 followup_patientstatus` == 'Deceased --> EXIT form' | `6 followup_patientstatus` == 'Deceased --> EXIT form' | `12 followup_patientstatus` == 'Deceased --> EXIT form' | `Point of exit from study` = 'Deceased', 'yes', 'no'))
  ) %>%

  filter(AI != '') %>%
  dplyr::select(
    `Age at enrolment, median (IQR) (years)` = `Age at enrolment`, 
`Gender, n(%)` = `Gender`,  `Ethnicity, n(%)` = Ethnicity, 
`Duration of current illness, median (IQR) (days)` = `Duration of current illness`, 
`Weight loss`, `Viral load (log10 Copies/mL)` = `log10 viral load`, 
Tuberculosis, `Cryptococcus neoformans`, Pneumonia, `Kaposis sarcoma`, 
HSV, HepB, Candida, `Total CD4 count`, 
`White cell count X109` = `White cell count`, 
`Lymphocyte count X109` = `Lymphocyte count`, 
Neutrophils, `Sodium mmol/L` = Sodium, `Potassium mmol/L` = Potassium, 
`Haemoglobin g/dL` = Haemoglobin, `BP (systolic)`, `BP (diastolic)`, 
`Any postural drop in blood pressure`, `Heart rate`, Hypotension, Weakness, 
Tiredness, `Poor appetite`, `Increased pigmentation of the skin`, 
Nausea, Vomiting, `Liking for salt`, Diarrhoea, Dizziness, Anorexia, 
`Loss of axillary and pubic hair, if female`, `Presence of anaemia`,
`ART exposure`, `Loss of consciousness`, Shock, Hypoglycaemia, mortality, 
Rifampicin, Fluconazole, Opiates, `Kidney medication`, `Kidney medication`, 
`Addisons disease`, `Staph aureus`, Cytomegalovirus, `Parvo B19`, `Syphilis`, 
`B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, 
PTB, EPTB,  `GE/c diff`, AI
                ) %>%
  mutate(`AI` = forcats::fct_rev(`AI`)) %>%
        tbl_summary( # table_1,
          missing = "no",
          by = `AI`,
          type = list(c("Duration of current illness, median (IQR) (days)", #"Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH", 
                        "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", "Age at enrolment, median (IQR) (years)", "Viral load (log10 Copies/mL)", "Total CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109", "Neutrophils") ~ "continuous"),#
          statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
    digits = list(all_categorical() ~ c(0, 1),
                  all_continuous() ~ c(1, 1))#,
    # label = list(`Total CD4 count...10` ~ "Total CD4 count")
  ) %>%
  add_p(test = list(all_categorical() ~ "fisher.test.simulate.p.values")) %>%
  # add_n() %>%
  # add_overall() %>%
  modify_header(label = "Variable") %>% # update the column header
  bold_labels()  %>%
  modify_caption('Table 3 (article): Should compare Total PAI with SAI patients')
  
 table_2_1

# tbl_merge(tbls = list(table_2, table_2_1),
#           tab_spanner = c("**Non-AI vs AI**", "** PAI vs SAI patients**"))
```

# Table 2.2: Cause of moratlity
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# table_2_2  <- cod_oi %>%
#   right_join(final_dataset %>%
#               dplyr::select(`Hospital folder number`, `Point of exit from study`, `Outcome of hospitalization`, addisons_disease, PAI, SAI, total_AI), 
#             by = 'Hospital folder number')
# # write.csv(table_2_2, 'table_2_2.csv')
# ```
# 
# ## cross-tabulation
# ```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# table_2_1 <- final_dataset %>%
#   mutate(Ethnicity = as.character(Ethnicity)) %>%
#   mutate(
#     `log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
#          `Age at enrolment` = as.numeric(`Age at enrolment`),
#          `Duration of current illness` = as.numeric(`Duration of current illness`),
#          `Total CD4 count` = as.numeric(`Total CD4 count...10`),
#          HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
#          `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
#          `Addisons disease`  = as.factor(ifelse(total_AI ==1, 'yes', ifelse(total_AI ==0, 'no', ''))),
#          Sodium = as.numeric(Sodium),
#          Potassium = as.numeric(Potassium),
#          Haemoglobin = as.numeric(Haemoglobin), 
#          `White cell count` = as.numeric(`White cell count`), 
#          `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
#          Neutrophils = as.numeric(Neutrophils),
#     Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
#     `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
#     `Random cortisol result` = as.numeric(`Random cortisol result`), 
#     `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
#     `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
#     `ACTH result` = as.numeric(`ACTH result`), 
#     `BP (systolic)` = as.numeric(`BP (systolic)`), 
#     `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
#     `Heart rate` = as.numeric(`Heart rate`)
#   ) %>%
#   filter(AI != '') %>%
#   dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, 
#     `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Random cortisol` = `Random cortisol result`, `Basal cortisol` = `Synacthen: 0 minute cortisol result`, `Stimulated cortisol` = `Synacthen: 30 minute cortisol result`, `ACTH` = `ACTH result`, `BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, `Presence of an opportunistic infection` = `Opportunistic infection present`, `Viral load (log10 Copies/mL)` = `log10 viral load`, `CD4 count` = `Total CD4 count`, `Sodium mmol/L` = Sodium, `Potassium mmol/L` = Potassium, `Haemoglobin g/dL` = Haemoglobin, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `3 followup_patientstatus`, `6 followup_patientstatus`, `12 followup_patientstatus`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `AI`#, `total AI` = total_AI
#                 ) %>%
#         tbl_summary( # table_1,
#           missing = "no",
#           by = `AI`,
#           type = list(c("Duration of current illness, median (IQR) (days)", "Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH", "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", "Age at enrolment, median (IQR) (years)", "Viral load (log10 Copies/mL)", "CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109", "Neutrophils") ~ "continuous"),#
#           statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
#           digits = list(all_categorical() ~ c(0, 1),
#                         all_continuous() ~ c(1, 1))
#         ) %>%
#         add_p() %>%
#         # add_overall() %>%
#         modify_header(label = "Variable") %>% # update the column header
#         bold_labels()  %>%
#   modify_caption('3.	Table 2: Should compare PAI with SAI patients')
# 
# table_2_1

# table_2_2 <- final_dataset %>%
#   mutate(Ethnicity = as.character(Ethnicity),
#          AI_recoded = ifelse(AI %in% c('PAI', 'SAI'), 'AI', 'No-AI')) %>%
#   mutate(
#     `log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
#          `Age at enrolment` = as.numeric(`Age at enrolment`),
#          `Duration of current illness` = as.numeric(`Duration of current illness`),
#          `Total CD4 count` = as.numeric(`Total CD4 count...10`),
#          HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
#          `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
#          # `Addisons disease`  = as.logical(addisons_disease),
#          Sodium = as.numeric(Sodium),
#          Potassium = as.numeric(Potassium),
#          Haemoglobin = as.numeric(Haemoglobin), 
#          `White cell count` = as.numeric(`White cell count`), 
#          `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
#          Neutrophils = as.numeric(Neutrophils),
#     Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
#     `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
#     `Random cortisol result` = as.numeric(`Random cortisol result`), 
#     `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
#     `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
#     `ACTH result` = as.numeric(`ACTH result`), 
#     `BP (systolic)` = as.numeric(`BP (systolic)`), 
#     `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
#     `Heart rate` = as.numeric(`Heart rate`),
#     `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`)
#   ) %>%
#   dplyr::select(`Age at enrolment, median (IQR) (years)` = `Age at enrolment`, 
#     `Gender, n(%)` = Gender, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Random cortisol` = `Random cortisol result`, `Basal cortisol` = `Synacthen: 0 minute cortisol result`, `Stimulated cortisol` = `Synacthen: 30 minute cortisol result`, `ACTH` = `ACTH result`, `BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection` = `Opportunistic infection present`,
#     `Viral load (log10 Copies/mL)` = `log10 viral load`, `CD4 count` = `Total CD4 count`, `Sodium mmol/L` = Sodium, `Potassium mmol/L` = Potassium, `Haemoglobin g/dL` = Haemoglobin, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `3 followup_patientstatus`, `6 followup_patientstatus`, `12 followup_patientstatus`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, AI_recoded#, `total AI` = total_AI
#                 ) %>%
#         tbl_summary( # table_1,
#           missing = "no",
#           by = `AI_recoded`,
#           type = list(c("Duration of current illness, median (IQR) (days)", "Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH", "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", "Age at enrolment, median (IQR) (years)", "Viral load (log10 Copies/mL)", "CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109", "Neutrophils") ~ "continuous"),#
#           statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
#           digits = list(all_categorical() ~ c(0, 1))
#         ) %>%
#         add_p() %>%
#         # add_overall() %>%
#         modify_header(label = "Variable") %>% # update the column header
#         bold_labels()
# 
# table_2_2

# table_2_3 <- tbl_merge(list(table_2_1, table_2_2))
# table_2_3
```


# Dotplot
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
dt02_2 <- final_dataset %>%
  filter(!is.na(as.numeric(`Synacthen: 30 minute cortisol result`))) %>%
  mutate(`Random cortisol result` = as.numeric(`Random cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Random cortisol result`) %>%
  mutate(group = 'Random')
dt02_1 <- final_dataset %>%
  filter(!is.na(as.numeric(`Synacthen: 30 minute cortisol result`))) %>%
  mutate(`Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Synacthen: 30 minute cortisol result`) %>%
  mutate(group = '+30 minute')
dt02 <- rbind(dt02_1, dt02_2) %>%
  mutate(group = as.factor(group)) %>%
  mutate(group = factor(group, levels=c('Random', '+30 minute')))

dt02_3 <- bind_rows(final_dataset %>%
  filter(PAI == 1) %>%
  mutate(`Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Synacthen: 0 minute cortisol result`) %>%
  mutate(group = 'Zero',
         AI = 'PAI'), 
  final_dataset %>%
  filter(PAI == 1) %>%
  filter(!is.na(as.numeric(`Synacthen: 30 minute cortisol result`))) %>%
    mutate(`Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Synacthen: 30 minute cortisol result`) %>%
  mutate(group = '+30 minute',
         AI = 'PAI')) 
  
dt02_4 <- bind_rows(final_dataset %>%
  filter(SAI == 1) %>%
  mutate(`Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Synacthen: 0 minute cortisol result`) %>%
  mutate(group = 'Zero',
         AI = 'SAI'), 
  final_dataset %>%
  filter(SAI == 1) %>%
  filter(!is.na(as.numeric(`Synacthen: 30 minute cortisol result`))) %>%
    mutate(`Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Synacthen: 30 minute cortisol result`) %>%
  mutate(group = '+30 minute',
         AI = 'SAI'))
dt02_5 <- bind_rows(dt02_4, dt02_3) %>%
  mutate(group = as.factor(group),
         AI = as.factor(AI)) %>%
  mutate(group = factor(group, levels=c('Zero', '+30 minute')),
         AI = factor(AI, levels=c('PAI', 'SAI')))
dt02_6 <- bind_rows(final_dataset %>%
  # filter(!is.na(`Synacthen: 30 minute cortisol result`)) %>%
  dplyr::select(`Hospital folder number`, value = `Random cortisol result`) %>%
  mutate(group = 'Random'),
  final_dataset %>%
  mutate(value = NA) %>%
  dplyr::select(`Hospital folder number`, value) %>%
  mutate(group = ''))

dot_plot1 <- ggplot(dt02, aes(x = group, y = value, fill = group)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize = 0.5) +
  geom_hline(yintercept = 500) +
  scale_fill_manual(values=c("#E7B800", "#2E9FDF")) +
  scale_y_continuous(breaks = seq(0, 1600, 100)) +
  theme(
    text = element_text(size = 18),
    axis.line = element_line(colour = "black"), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), panel.background = element_blank(),
    panel.border = element_blank(),
    aspect.ratio = 1,
    plot.margin = unit(c(0, 0, 0, 0), "lines"),
    legend.position = "none")# +
  # ggtitle('A')
dot_plot1
dot_plot2 <- ggplot(dt02_5, aes(x = AI, y = value, fill = group)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize = 1,
               position=position_dodge(0.8)) +
  geom_hline(yintercept = 500) +
  scale_fill_manual(values=c("#E7B800", "#2E9FDF")) + #ylim(0, 1600) +
  scale_y_continuous(breaks = seq(0, 1600, 100)) +
  theme(
    text = element_text(size = 18),
    axis.line = element_line(colour = "black"), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), panel.background = element_blank(),
    panel.border = element_blank(),
    aspect.ratio = 1,
    plot.margin = unit(c(0, 0, 0, 0), "lines")#,
    # legend.position = "none"
    ) #+
  # ggtitle('B')
dot_plot2

dot_plot3 <- ggplot(dt02_6 %>% 
                      mutate(value = as.numeric(value),
                             group = as.factor(group)), aes(x = group, y = value, fill = group)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize = 0.5) +
  geom_hline(yintercept = 500) +
  scale_fill_manual(values=c("#E7B800", "#2E9FDF")) +
  scale_y_continuous(breaks = seq(0, 1600, 100)) +
  theme(
    text = element_text(size = 18),
    axis.line = element_line(colour = "black"), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), panel.background = element_blank(),
    panel.border = element_blank(),
    aspect.ratio = 1,
    plot.margin = unit(c(0, 0, 0, 0), "lines"),
    legend.position = "none") +
  ggtitle('A')
dot_plot3

jpeg('dot_plot1.png', units = "in", width = 8, height = 9, res = 300)
# ggarrange(dot_plot1, dot_plot2, #labels = c("A", "B"),
                    # ncol = 2, nrow = 1)
dot_plot1

dev.off()

jpeg('dot_plot2.png', units = "in", width = 8, height = 9, res = 300)
# ggarrange(dot_plot1, dot_plot2, #labels = c("A", "B"),
                    # ncol = 2, nrow = 1)
dot_plot2

dev.off()

jpeg('dot_plot3.png', units = "in", width = 8, height = 9, res = 300)
# ggarrange(dot_plot1, dot_plot2, #labels = c("A", "B"),
                    # ncol = 2, nrow = 1)
dot_plot3

dev.off()

```

# Table 3: Bivariate table

```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
table_mortality <- final_dataset %>%
  dplyr::select(`Hospital folder number`, `3 followup_patientstatus`, `6 followup_patientstatus`, `12 followup_patientstatus`) %>%
  pivot_longer(cols = c(`3 followup_patientstatus`, `6 followup_patientstatus`, `12 followup_patientstatus`),
               names_to = 'col_num',
               values_to = 'followup_patientstatus') %>%
  dplyr::select(`Hospital folder number`, `followup_patientstatus`) %>%
  group_by(`Hospital folder number`) %>%
  mutate(mortality = ifelse(followup_patientstatus == 'Deceased --> EXIT form', 1,ifelse(followup_patientstatus == 'Alive', 0, 0))) %>%
  dplyr::select(`Hospital folder number`, mortality)
table_mortality[is.na(table_mortality)] <- 0
table_mortality1 <- table_mortality %>%
  group_by(`Hospital folder number`) %>%
  mutate(mortality = max(mortality)) %>%
  distinct(`Hospital folder number`, .keep_all = T)

time_to_death <- final_dataset%>%
  dplyr::select(`Hospital folder number`, `3 followup_patientstatus`,
                `6 followup_patientstatus`, `12 followup_patientstatus`
                ) %>%
  mutate(flag1 = ifelse(`3 followup_patientstatus` == "Deceased --> EXIT form", 3, NA),
         flag2 = ifelse(`6 followup_patientstatus` == "Deceased --> EXIT form", 6, NA),
         flag3 = ifelse(`12 followup_patientstatus` == "Deceased --> EXIT form", 12, NA)) %>%
  dplyr::select(`Hospital folder number`, flag1:flag3) %>%
  pivot_longer(cols = c(flag1:flag3),
               names_to = 'col_num',
               values_to = 'time to death') %>%
  dplyr::select(`Hospital folder number`, `time to death`) %>%
  group_by(`Hospital folder number`) %>%
  mutate(ttdeath = min(`time to death`, na.rm = T)) %>%
  ungroup() %>%
  mutate(ttdeath = ifelse(is.infinite(ttdeath), 12, ttdeath)) %>%
  distinct(`Hospital folder number`, .keep_all = T) %>%
    dplyr::select(`Hospital folder number`, ttdeath)

interval_deaths <- final_dataset%>%
  dplyr::select(`Hospital folder number`, `3 followup_patientstatus`,
                `6 followup_patientstatus`, `12 followup_patientstatus`
                ) %>%
  mutate(flag1 = ifelse(`3 followup_patientstatus` == "Deceased --> EXIT form", 3, NA),
         flag2 = ifelse(`6 followup_patientstatus` == "Deceased --> EXIT form", 6, NA),
         flag3 = ifelse(`12 followup_patientstatus` == "Deceased --> EXIT form", 12, NA)) %>%
  dplyr::select(`Hospital folder number`, flag1:flag3) %>%
  pivot_longer(cols = c(flag1:flag3),
               names_to = 'col_num',
               values_to = 'time to death') %>%
  dplyr::select(`Hospital folder number`, `time to death`) %>%
  group_by(`Hospital folder number`) %>%
  mutate(ttdeath = min(`time to death`, na.rm = T)) %>%
  ungroup()
x <- interval_deaths %>% filter(!is.na(`time to death`))%>% distinct(`Hospital folder number`, .keep_all = T)
# table(x$ttdeath)

table_mortality1 <- table_mortality1 %>%
  left_join(time_to_death, by = 'Hospital folder number')

table_3 <- final_dataset %>%
  left_join(table_mortality1, by = 'Hospital folder number') %>%
  mutate(Ethnicity = as.character(Ethnicity),
         mortality = ifelse(`Point of exit from study` == 'Deceased', 1, 0)) %>%
  mutate(mortality = ifelse(is.na(mortality), 0, mortality)) %>%
  mutate(
    `log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
    discharged = ifelse(!is.na(`Date of discharge`), 'Yes', 'No'),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(addisons_disease),
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin), 
         `White cell count` = as.numeric(`White cell count`), 
         `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
         Neutrophils = as.numeric(Neutrophils),
    Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
    `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
    `Random cortisol result` = as.numeric(`Random cortisol result`), 
    `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
    `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
    `ACTH result` = as.numeric(`ACTH result`), 
    `BP (systolic)` = as.numeric(`BP (systolic)`), 
    `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
    `Heart rate` = as.numeric(`Heart rate`),
    `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
    AI_recoded = as.factor(ifelse(AI %in% c('PAI', 'SAI') | UIN...1 %in% c(392, 435, 478, 488, 496, 500), 'AI', 'No-AI')),
    mortality = ifelse(`Point of exit from study` == 'Deceased', 1,  0)) %>%
  mutate(mortality = ifelse(is.na(mortality), 0, mortality)) %>%
  dplyr::select(`Age at enrolment`, Gender, Ethnicity, `Duration of current illness`, `log10 viral load`, `Total CD4 count`, Sodium, Potassium, Haemoglobin, `White cell count`, `Lymphocyte count`, Neutrophils, `Addisons disease`, mortality, ttdeath, `Random cortisol result`, `Synacthen: 0 minute cortisol result`, `Synacthen: 30 minute cortisol result`, `ACTH result`, `BP (systolic)`, `BP (diastolic)`, discharged,
                `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection` = `Opportunistic infection present`,
                Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Date of enrolment in study`, `HIV, when diagnosed`, AI_recoded, AI, total_AI, `ART exposure`, `Kidney medication`, incremental_cortisol, Rifampicin, Fluconazole, Opiates) %>%
  mutate(Ethnicity = as.factor(Ethnicity),
         Gender = as.factor(Gender),
         Addisons_disease = as.numeric(as.factor(`Addisons disease`)),
         Log10_viralload = `log10 viral load`,
         Age_at_enrolment = `Age at enrolment`,
         Total_CD4_count = `Total CD4 count`,
         White_cell_count = `White cell count`,
         Lymphocyte_count = `Lymphocyte count`,
         Duration_of_current_illness = `Duration of current illness`) %>%
  dplyr::select(Age_at_enrolment, Gender, Ethnicity, Duration_of_current_illness, `Viral load (log10 Copies/mL)` = Log10_viralload, `CD4 count` = Total_CD4_count, Sodium, `Potassium mmol/L` = Potassium, Haemoglobin, White_cell_count, Lymphocyte_count, Neutrophils, Addisons_disease, mortality, ttdeath,
                `Random cortisol` = `Random cortisol result`, `Basal cortisol` = `Synacthen: 0 minute cortisol result`, `Stimulated cortisol` = `Synacthen: 30 minute cortisol result`, `ACTH` = `ACTH result`, `BP (systolic)`, `BP (diastolic)`, `Addisons disease`, discharged, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection`, 
                Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Date of enrolment in study`, `HIV, when diagnosed`, AI_recoded, AI, total_AI, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates, incremental_cortisol)

# tbl_uvregression(
#   table_3,
#   method=coxph,
#   y = Surv(time = ttdeath, event = mortality),
#   exponentiate = TRUE#,
#   # include = -ID
# )
interval_deaths_addissons <- interval_deaths %>% filter(!is.na(`time to death`))%>% distinct(`Hospital folder number`, .keep_all = T) %>% filter(`Hospital folder number` %in% c('GSH 167073 154', 'GSH 170759 435', 'GSH 70197 710', 'GSH 79071 908', 'GSH 83628 503'))
```


# Table 3a: Deep dive on Addison's disease patients

```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
table_4 <- table_3 %>%
  filter(mortality == 1) %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y'))
         ) %>%
  dplyr::select(
    `Age at enrolment, median (IQR) (years)` = Age_at_enrolment, 
`Gender, n(%)` = `Gender`, 
`Duration of current illness, median (IQR) (days)` = Duration_of_current_illness, 
`Random cortisol`, `Basal cortisol`, `Stimulated cortisol`, incremental_cortisol, 
`Weight loss`, `Viral load (log10 Copies/mL)`, PTB, EPTB,  `Cryptococcus neoformans`, 
Pneumonia, HSV, HepB, Candida, `Syphilis`, PCP, `Total CD4 count` = `CD4 count`, 
`White cell count X109` = White_cell_count, `Sodium mmol/L` = Sodium, 
`Potassium mmol/L`, `Haemoglobin g/dL` = Haemoglobin, `Presence of anaemia`, 
`BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, 
Tiredness, `Poor appetite`, `Increased pigmentation of the skin`, Nausea, 
Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, 
Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, 
`Any postural drop in blood pressure`, `ART exposure`, `Kidney medication`, 
`ACTH`, Rifampicin, Fluconazole, Opiates, `Addisons disease` = Addisons_disease,
`Ethnicity, n(%)` = Ethnicity, Tuberculosis, `Staph aureus`, `Kaposis sarcoma`, 
Cytomegalovirus, `GE/c diff`, `Parvo B19`, `B menigitis`, `UTI / Leptospirosis`, 
`COVID-19`, `Neurocysticercosis`, `Lymphocyte count X109` = Lymphocyte_count, 
Neutrophils) %>%
  # mutate(`Addisons disease` = forcats::fct_rev(`Addisons disease`)) %>%
tbl_summary(#table_1,
            missing = "no",
            by = `Addisons disease`,
            digits = list(all_categorical() ~ c(0, 1)),
            ) %>%
  add_p() %>%
  # add_n() %>%
  modify_header(label = "Variable") %>%
  bold_labels() %>%
  modify_caption('Table 4 (article): Mortality: Non-AI vs AI')
table_4
dt04 <- table_3 %>%
  mutate(flag = ifelse(Addisons_disease == 2 & mortality == 1, 'AI deaths', 
                       ifelse(Addisons_disease == 1 & mortality == 0, 'Alive without AI', ''))) %>%
  filter(flag != '') %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y'))#,
         # gender = factor(gender, labels = c('Females', 'Males')),
         # Ethnicity = ifelse(Ethnicity== 'Asian' | Ethnicity== 'Coloured' | Ethnicity== 'White', 'Other', Ethnicity),
  ) %>%
  dplyr::select(
    `Age at enrolment, median (IQR) (years)` = Age_at_enrolment, `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = Duration_of_current_illness, `Weight loss`, `Viral load (log10 Copies/mL)`, Tuberculosis, `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Total CD4 count` = `CD4 count`, `White cell count X109` = White_cell_count, `Lymphocyte count X109` = Lymphocyte_count, Neutrophils, `Sodium mmol/L` = Sodium, `Potassium mmol/L`, `Haemoglobin g/dL` = Haemoglobin, 
    `BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection`, 
    `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates, incremental_cortisol, flag) %>% #`Addisons disease` = Addisons_disease
  # mutate(`Addisons disease` = forcats::fct_rev(`Addisons disease`)) %>%
  tbl_summary(#table_1,
    missing = "no",
    by = flag,#`Addisons disease`,
    digits = list(all_categorical() ~ c(0, 1)),
  ) %>%
  add_p() %>%
  # add_n() %>%
  modify_header(label = "Variable") %>%
  bold_labels() %>%
  modify_caption('Mortality: Non-AI vs AI')
dt04
```

<!-- # Table 3b: Deep dive in mortality between PAI and SAI -->
```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
table_4_1 <- table_3 %>%
  filter(mortality == 1) %>%
  filter(`Addisons disease` == 1) %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
    `mortality with Addisons disease` = ifelse(mortality == 1, 'Die', 'no'),
    # gender = factor(gender, labels = c("Females", "Males")),
    # Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", Ethnicity)
  ) %>%
  dplyr::select(`mortality with Addisons disease`, `Age at enrolment median (IQR) (years)` = Age_at_enrolment, `Gender, n(%)` = Gender, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = HIV_duration, `Random cortisol`, `Basal cortisol`, `Stimulated cortisol`, `ACTH`, incremental_cortisol, `BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection`, 
                Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Viral load (log10 Copies/mL)`, `Total CD4 count` = `CD4 count`, `Sodium mmol/L` = Sodium, `Potassium mmol/L`, `Haemoglobin g/dL` = Haemoglobin, `White cell count X109` = White_cell_count, `Lymphocyte count X109` = Lymphocyte_count, AI, `Addisons disease`, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates) %>%
  mutate(`mortality with Addisons disease` = forcats::fct_rev(`mortality with Addisons disease`)) %>%
  tbl_summary( # table_1,
    missing = "no",
    by = AI,
    # type = list(c("Age at enrolment median (IQR) (years)", "Duration of current illness, median (IQR) (days)", "Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH", "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", #"Age at enrolment, median (IQR) (years)",
    #               "`Viral load (log10 Copies/mL)", "Total CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109") ~ "continuous"),#, "Neutrophils"
    #       statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
          digits = list(all_categorical() ~ c(0, 1),
                        all_continuous() ~ c(1, 1))
  ) %>%
  add_p() %>%
  # add_n() %>%
modify_header(label = "Variable") %>%
bold_labels()  %>%
  modify_caption('Table 2.2.1: Mortality; PAI SAI')

table_4_1


table_4_2 <- table_3 %>%
  # filter(mortality == 1) %>%
  filter(`Addisons disease` == 1) %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
    `mortality with Addisons disease` = ifelse(mortality == 1, 'Died', 'Alive'),
    # gender = factor(gender, labels = c("Females", "Males")),
    # Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", Ethnicity)
  ) %>%
  dplyr::select(`mortality with Addisons disease`, `Age at enrolment median (IQR) (years)` = Age_at_enrolment, `Gender, n(%)` = Gender, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = HIV_duration, `Random cortisol`, `Basal cortisol`, `Stimulated cortisol`, `ACTH`, incremental_cortisol, `BP (systolic)`, `BP (diastolic)`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection`, 
                Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Viral load (log10 Copies/mL)`, `Total CD4 count` = `CD4 count`, `Sodium mmol/L` = Sodium, `Potassium mmol/L`, `Haemoglobin g/dL` = Haemoglobin, `White cell count X109` = White_cell_count, `Lymphocyte count X109` = Lymphocyte_count, `Addisons disease` = AI, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates) %>% #, `Addisons disease`
  # mutate(`mortality with Addisons disease` = forcats::fct_rev(`mortality with Addisons disease`)) %>%
  tbl_summary( # table_1,
    missing = "no",
    by = `mortality with Addisons disease`,
    # type = list(c("Age at enrolment median (IQR) (years)", "Duration of current illness, median (IQR) (days)", "Random cortisol", "Basal cortisol", "Stimulated cortisol", "ACTH", "BP (systolic)", "BP (diastolic)", "Potassium mmol/L", #"Age at enrolment, median (IQR) (years)",
    #               "`Viral load (log10 Copies/mL)", "Total CD4 count", "White cell count X109", "Haemoglobin g/dL", "Sodium mmol/L", "Heart rate", "Lymphocyte count X109") ~ "continuous"),#, "Neutrophils"
    #       statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
          digits = list(all_categorical() ~ c(0, 1),
                        all_continuous() ~ c(1, 1))
  ) %>%
  add_p() %>%
  # add_n() %>%
modify_header(label = "Variable") %>%
bold_labels()  %>%
  modify_caption('Table 2.2.2: Mortality among only Addisons disease patients')

# table_4_2
tbl_merge(tbls = list(table_4, table_4_2),
          tab_spanner = c("**Mortality: Non-AI vs AI**", "** Mortality among only Addisons disease patients**"))
```



```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
univariate_mortality <- tbl_uvregression(
  table_3 %>%
    mutate(
      HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format = "%m/%d/%Y") - as.Date(`HIV, when diagnosed`, format = "%m/%d/%Y")),
      `mortality with Addisons disease` = ifelse(mortality == 1, "yes", "no"),
      incremental_cortisol = incremental_cortisol/50,
      `ACTH` = `ACTH`/50,
      `Random cortisol` = `Random cortisol`/50,
      `Basal cortisol` = `Basal cortisol`/50,
      `Stimulated cortisol` = `Stimulated cortisol`/50
    ) %>%
    dplyr::select(Age_at_enrolment, Gender, Ethnicity, # HIV_duration,
      Random_cortisol = `Random cortisol`, Basal_cortisol = `Basal cortisol`, Stimulated_cortisol = `Stimulated cortisol`, `ACTH`, BP_systolic = `BP (systolic)`, BP_diastolic = `BP (diastolic)`, incremental_cortisol, Heart_rate = `Heart rate`, Hypotension, Weakness, Tiredness, Poor_appetite = `Poor appetite`, Weight_loss = `Weight loss`, Increased_pigmentation_of_the_skin = `Increased pigmentation of the skin`, Nausea, Vomiting, Liking_for_salt = `Liking for salt`, Hypoglycaemia, Loss_of_consciousness = `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, Loss_of_axillary_and_pubic_hair = `Loss of axillary and pubic hair, if female`, Any_postural_drop_in_blood_pressure = `Any postural drop in blood pressure`, Presence_of_anaemia = `Presence of anaemia`, # Presence_of_an_opportunistic_infection = `Presence of an opportunistic infection`,
      Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`,
      Viral_load = `Viral load (log10 Copies/mL)`, CD4_count = `CD4 count`, Sodium, Potassium = `Potassium mmol/L`, Haemoglobin, White_cell_count, Lymphocyte_count, `ART exposure`, `Kidney medication`, Rifampicin, Fluconazole, Opiates, Addisons_disease = `Addisons disease`, ttdeath, mortality
    ), # table_3,
  method = glm,
  y = mortality,
  exponentiate = TRUE # ,
  # include = -ID
)
```

# Table 4: Multivariate table mortality

<!-- The rule of thumb for MV models such as this on you need at least 10 people per outcome. We have 53 people with the outcome, yet we have 6 variables adjusted for in the model (using stepwise regression). I suggest we remove one variable from the list that you think may not be biologically contributing in the relationship. (see accompanying file) -->

```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
# Step 1: Calculate the percentage of missing values in each column
missing_percentage <- sapply(table_3, function(x) mean(is.na(x))) * 100

# Step 2: Identify columns with 30% or more missing data
columns_to_impute <- names(missing_percentage[missing_percentage <= 30])

dt <- table_3[, columns_to_impute] %>%
  dplyr::select(
    Age_at_enrolment, Gender, Ethnicity, Duration_of_current_illness, cd4 = `CD4 count`, Sodium, 
    Potassium_mmol_L = `Potassium mmol/L`, Haemoglobin, White_cell_count, mortality, 
    Random_cortisol = `Random cortisol`, ACTH, BP_systolic = `BP (systolic)`, 
    BP_diastolic = `BP (diastolic)`, 
    Addisons_disease = `Addisons disease`, discharged, Heart_rate = `Heart rate`, Hypotension, 
    Weakness, Tiredness, Poor_appetite = `Poor appetite`, Weight_loss = `Weight loss`, 
    Increased_pigmentation_skin = `Increased pigmentation of the skin`, Nausea, Vomiting, 
    Liking_for_salt = `Liking for salt`, Hypoglycaemia, 
    Loss_of_consciousness = `Loss of consciousness`, 
    Diarrhoea, Dizziness, Shock, Anorexia, 
    Any_postural_drop_in_blood_pressure = `Any postural drop in blood pressure`, 
    Presence_of_anaemia = `Presence of anaemia`, PTB, EPTB, 
    Cryptococcus_neoformans = `Cryptococcus neoformans`, 
    Pneumonia, Staph_aureus = `Staph aureus`, Kaposis_sarcoma = `Kaposis sarcoma`, 
    Cytomegalovirus, HSV, HepB, 
    Candida, GE_c_diff = `GE/c diff`, Parvo_B19 = `Parvo B19`, 
    Syphilis, B_menigitis = `B menigitis`, 
    UTI_Leptospirosis = `UTI / Leptospirosis`, PCP, COVID_19 = `COVID-19`, Neurocysticercosis,
    ART_exposure = `ART exposure`, Kidney_medication = `Kidney medication`, Rifampicin, 
    Fluconazole, Opiates) %>%
  mutate(Gender = as.numeric(Gender),
         Ethnicity = as.numeric(Ethnicity),
         Addisons_disease = as.null(Addisons_disease),
         discharged = as.numeric(as.factor(discharged)),
         Hypotension = as.numeric(Hypotension),
         Weakness = as.numeric(Weakness),
         Tiredness  = as.numeric(Tiredness),
         Poor_appetite = as.numeric(Poor_appetite),
         Weight_loss = as.numeric(Weight_loss),
         Increased_pigmentation_skin = as.numeric(Increased_pigmentation_skin),
         Nausea = as.numeric(Nausea),
         Vomiting = as.numeric(Vomiting),
         Liking_for_salt = as.numeric(Liking_for_salt),
         Hypoglycaemia = as.numeric(Hypoglycaemia),
         Loss_of_consciousness = as.numeric(Loss_of_consciousness),
         Diarrhoea = as.numeric(Diarrhoea),
         Dizziness = as.numeric(Dizziness),
         Shock = as.numeric(Shock),
         Anorexia = as.numeric(Anorexia),
         Any_postural_drop_in_blood_pressure = as.numeric(Any_postural_drop_in_blood_pressure),
         Presence_of_anaemia = as.numeric(Presence_of_anaemia),
         PTB = as.numeric(PTB),
         EPTB = as.numeric(EPTB),
         Cryptococcus_neoformans = as.numeric(Cryptococcus_neoformans),
         Pneumonia = as.numeric(Pneumonia),
         Staph_aureus = as.numeric(Staph_aureus),
         Kaposis_sarcoma = as.numeric(Kaposis_sarcoma),
         Cytomegalovirus = as.numeric(Cytomegalovirus),
         HSV = as.numeric(HSV),
         HepB = as.numeric(HepB),
         Candida = as.numeric(Candida),
         GE_c_diff = as.numeric(GE_c_diff),
         Parvo_B19 = as.numeric(Parvo_B19),
         Syphilis = as.numeric(Syphilis),
         B_menigitis = as.numeric(B_menigitis),
         UTI_Leptospirosis = as.numeric(UTI_Leptospirosis),
         PCP = as.numeric(PCP),
         COVID_19 = as.numeric(COVID_19),
         Neurocysticercosis = as.numeric(Neurocysticercosis),
         ART_exposure = as.numeric(ART_exposure),
         Kidney_medication = as.numeric(Kidney_medication),
         Rifampicin = as.numeric(Rifampicin),
         Fluconazole = as.numeric(Fluconazole),
         Opiates = as.numeric(Opiates)
         )

# Calculate the correlation matrix
cor_matrix <- cor(dt, use = "pairwise.complete.obs")

# Find columns with correlation > 0.8 (excluding self-correlations)
high_cor_pairs <- findCorrelation(cor_matrix, cutoff = 0.7)

# Drop highly correlated variables
data_reduced <- dt[, -high_cor_pairs]

# selecting variables to analysis  for bivariate analysis
covariates <- names(data_reduced)[sapply(data_reduced, is.numeric)][-which(names(data_reduced) == "mortality")]

# Perform univariate regression
univariate_models <- lapply(covariates, function(x) {
  formula <- as.formula(paste("mortality ~ ", x))
  lm(formula, data = data_reduced)
})

# Extract coefficients and p-values
univariate_results <- lapply(univariate_models, tidy)

# Bind results into a single data frame
results_df <- do.call(rbind, univariate_results)

# Filter models with P < 0.2
selected_models <- results_df %>%
  filter(term != '(Intercept)')%>%
  filter(p.value <= 0.2) %>%
  arrange(p.value)

data_to_impute <- data_reduced %>%
  dplyr::select(mortality, selected_models$term)
univariate_table <- tbl_uvregression(
          data_to_impute %>% 
            dplyr::select(mortality, selected_models$term) %>% 
            mutate(Random_cortisol = Random_cortisol/50, 
                   # BP_systolic = BP_systolic/10, 
                   BP_diastolic = BP_diastolic/10),
          method = glm,
          y = mortality,
          method.args = list(family = binomial),
          exponentiate = TRUE#,
          # include = -ID
        )
univariate_table

# nr_imputations <- 5
# 
# imputedData <- mice::mice(
#   data =data.frame(data_reduced %>% dplyr::select(-mortality)),#data.frame(dt[, columns_to_impute]),
#   m = nr_imputations,
#   maxit = 20,
#   defaultMethod = c("pmm", "logreg", "polyreg", "polr"),
#   seed = 33#,
#   )
# 
# completeData_mort <- bind_cols(data_reduced %>%
#                             dplyr::select(mortality),
#                           aggregate(complete(imputedData, 'long')[,3:length(complete(imputedData, 'long'))],
#                                         by = list(complete(imputedData, 'long')$.id),
#                                         FUN= mean)
# )  %>%
#   mutate(Weakness = ifelse(Weakness <0.5, 0, 1),
#          # Tiredness = ifelse(Tiredness <0.5, 0, 1),
#          Poor_appetite = ifelse(Poor_appetite <0.5,0, 1),
#          # Increased_pigmentation_of_the_skin = ifelse(Increased_pigmentation_of_the_skin <0.5, 0, 1),
#          Nausea = ifelse(Nausea < 0.5, 0, 1),
#          Liking_for_salt = ifelse(Liking_for_salt < 0.5, 0, 1),
#          Loss_of_consciousness = ifelse(Loss_of_consciousness < 0.5, 0, 1),
#          Diarrhoea = ifelse(Diarrhoea <0.5, 0, 1),
#          # Dizziness = ifelse(Dizziness < 0.5, 0, 1),
#          Shock = ifelse(Shock < 0.5, 0, 1),
#          # Anorexia = ifelse(Anorexia < 0.5, 0, 1),
#          Cryptococcus_neoformans = ifelse(Cryptococcus_neoformans < 0.5, 0, 1),
#          PCP = ifelse(PCP < 0.5, 0, 1)#,
#          # Loss_of_axillary_and_pubic_hair = ifelse(Loss_of_axillary_and_pubic_hair <1.5, 1,
#                                                   # ifelse(Loss_of_axillary_and_pubic_hair >= 1.5 & Loss_of_axillary_and_pubic_hair <2.5, 2,3))
#          ) %>% dplyr::select(-Group.1)

# saveRDS(completeData_mort, 'completeData_mort.rds')

completeData_mort_allvars <- readRDS('completeData_mort.rds')

control <- rfeControl(functions = rfFuncs, # random forest
                      method = "cv", # repeated cvrepeated
                      # repeats = 3, # number of repeats
                      number = 5) # number of folds

results <- rfe(completeData_mort[,c(2:length(completeData_mort))], completeData_mort[[1]], rfeControl = control)
var_selected <- predictors(results)

tc <- trainControl(method = "cv", 
                   number = 5, 
                   classProbs = TRUE,
                   savePredictions = TRUE#,
                   # summaryFunction = twoClassSummary
                   )

model2 <- train(mortality ~ .,
  data = completeData_mort %>% dplyr::select(mortality, var_selected) %>% mutate(Random_cortisol = Random_cortisol/50, BP_systolic = BP_systolic/10, BP_diastolic = BP_diastolic/10),
  method = "glm",
  # metric = 'ROC',
  trControl = tc,
  family = binomial(link = "logit")
)
summary(model2)

```


# Table 5 univariate analysis for addisson's disease

```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}

table_5 <- final_dataset %>%
  left_join(table_mortality1, by = 'Hospital folder number') %>%
  mutate(Ethnicity = as.character(Ethnicity)) %>%
  mutate(
    `log10 viral load` = log(as.numeric(`HIV viral load`, 10)),
         `Age at enrolment` = as.numeric(`Age at enrolment`),
         `Duration of current illness` = as.numeric(`Duration of current illness`),
         `Total CD4 count` = as.numeric(`Total CD4 count...10`),
    discharged = ifelse(!is.na(`Date of discharge`), 'Yes', 'No'),
         HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
         `Gender` = (ifelse(Gender == 'NA', 'Unknown', Gender)),
         `Addisons disease`  = as.factor(ifelse(total_AI ==1, 'yes', ifelse(total_AI ==0, 'no', ''))),
         Sodium = as.numeric(Sodium),
         Potassium = as.numeric(Potassium),
         Haemoglobin = as.numeric(Haemoglobin), 
         `White cell count` = as.numeric(`White cell count`), 
         `Lymphocyte count` = as.numeric(`Lymphocyte count`), 
         Neutrophils = as.numeric(Neutrophils),
    Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", ifelse(Ethnicity == 'NA', 'Unknown', Ethnicity)),
    `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
    `Random cortisol result` = as.numeric(`Random cortisol result`), 
    `Synacthen: 0 minute cortisol result` = as.numeric(`Synacthen: 0 minute cortisol result`),
    `Synacthen: 30 minute cortisol result` = as.numeric(`Synacthen: 30 minute cortisol result`), 
    `ACTH result` = as.numeric(`ACTH result`), 
    `BP (systolic)` = as.numeric(`BP (systolic)`), 
    `BP (diastolic)` = as.numeric(`BP (diastolic)`), 
    `Heart rate` = as.numeric(`Heart rate`),
    `Toxoplasmosis` = as.factor(`Opportunistic infection  (choice=Toxoplasmosis)`),
    mortality = as.factor(ifelse(`3 followup_patientstatus` == 'Deceased --> EXIT form' | `6 followup_patientstatus` == 'Deceased --> EXIT form' | `12 followup_patientstatus` == 'Deceased --> EXIT form', 'yes', 'no'))
    # `Mycobacterium avium-intracellulare` = as.factor(`Opportunistic infection  (choice=Mycobacterium avium-intracellulare)`),
    # `Kaposis sarcoma` = as.factor(`Opportunistic infection  (choice=Kaposis sarcoma)`),
    # `Cytomegalovirus` = as.factor(`Opportunistic infection  (choice=Cytomegalovirus)`),
    # `Other` = as.factor(`Opportunistic infection  (choice=Other)`),
    # `Loss of axillary and pubic hair, if female` != "Not applicable"
  ) %>%
  dplyr::select(`Age at enrolment`, Gender, Ethnicity, `Duration of current illness`, `log10 viral load`, `Total CD4 count`, Sodium, Potassium, Haemoglobin, `White cell count`, `Lymphocyte count`, Neutrophils, `Addisons disease`, mortality, ttdeath, `Random cortisol result`, `Synacthen: 0 minute cortisol result`, `Synacthen: 30 minute cortisol result`, `ACTH result`, incremental_cortisol, `BP (systolic)`, `BP (diastolic)`, discharged,
                `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Weight loss`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, `Loss of axillary and pubic hair, if female`, `Any postural drop in blood pressure`, `Presence of anaemia`, #`Presence of an opportunistic infection` = `Opportunistic infection present`,
                Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Date of enrolment in study`, `HIV, when diagnosed`, AI, `ART exposure`, `Kidney medication`, mortality) %>%
  mutate(Ethnicity = as.numeric(as.factor(Ethnicity)),
         Gender = as.factor(Gender),
         Addisons_disease = as.numeric(as.factor(`Addisons disease`)),
         Log10_viralload = `log10 viral load`,
         Age_at_enrolment = `Age at enrolment`,
         Total_CD4_count = `Total CD4 count`,
         White_cell_count = `White cell count`,
         Lymphocyte_count = `Lymphocyte count`,
         Duration_of_current_illness = `Duration of current illness`,
         AI_recoded = as.factor(ifelse(AI %in% c('PAI', 'SAI'), 'AI', 'No-AI')),
         # Tuberculosis = as.factor(ifelse(`Tuberculosis`== 'Checked', 'Yes', 'No')),
         # Other = as.factor(ifelse(Other== 'Checked', 'Yes', 'No')),
         `Random cortisol result` = `Random cortisol result`/10, 
         `Synacthen: 0 minute cortisol result` = `Synacthen: 0 minute cortisol result`/10, 
         `Synacthen: 30 minute cortisol result` = `Synacthen: 30 minute cortisol result`/10, 
         `ACTH result` = `ACTH result`/10,
         Total_CD4_count = Total_CD4_count/5, 
         Sodium = Sodium/5, 
         Potassium = Potassium /5, 
         White_cell_count = White_cell_count/5, 
         Lymphocyte_count = Lymphocyte_count /5, 
         Neutrophils = ifelse(Neutrophils==953, NA, Neutrophils)/5,
         # `3 followup_patientstatus` = ifelse(`3 followup_patientstatus` == 'NA', 'Alive', `3 followup_patientstatus`),
         # `6 followup_patientstatus` = ifelse((`3 followup_patientstatus` == 'Alive' & `6 followup_patientstatus` == 'NA'), 'Alive', `6 followup_patientstatus` ),
         # `12 followup_patientstatus` = ifelse((`3 followup_patientstatus` == 'Alive' & `6 followup_patientstatus` == 'Alive' & `12 followup_patientstatus` == 'NA'), 'Alive', `12 followup_patientstatus`),
         Duration_of_current_illness = Duration_of_current_illness/10
         ) %>%
  dplyr::select(
    `Age at enrolment`, `Gender, n(%)` = `Gender`, `Ethnicity, n(%)` = Ethnicity, `Duration of current illness, median (IQR) (days)` = `Duration of current illness`, `Weight loss`, `log10 viral load`, Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`, `Total CD4 count`, `White cell count X109` = `White cell count`, `Lymphocyte count X109` = `Lymphocyte count`, Neutrophils, `Sodium mmol/L` = Sodium, `Potassium mmol/L` = Potassium, `Haemoglobin g/dL` = Haemoglobin, 
    
    `BP (systolic)`, `BP (diastolic)`, `Any postural drop in blood pressure`, `Heart rate`, Hypotension, Weakness, Tiredness, `Poor appetite`, `Increased pigmentation of the skin`, Nausea, Vomiting, `Liking for salt`, Hypoglycaemia, `Loss of consciousness`, Diarrhoea, Dizziness, Shock, Anorexia, #`Loss of axillary and pubic hair, if female`, 
    `Presence of anaemia`, `ART exposure`, `Kidney medication`, mortality, #`Presence of an opportunistic infection`, 
                # `White cell count X109` = White_cell_count, `Lymphocyte count X109` = Lymphocyte_count, Neutrophils, `3 followup_patientstatus`, `6 followup_patientstatus`, `12 followup_patientstatus`, #mortality, ttdeath,
                # Tuberculosis, PTB, EPTB,  `Cryptococcus neoformans`, Pneumonia, `Staph aureus`, `Kaposis sarcoma`, Cytomegalovirus, HSV, HepB, Candida, `GE/c diff`, `Parvo B19`, `Syphilis`, `B menigitis`, `UTI / Leptospirosis`, PCP, `COVID-19`, `Neurocysticercosis`,
                AI_recoded) #%>%
   
tbl_uvregression(
  table_5 %>%
    mutate(AI_recoded = ifelse(as.character(AI_recoded)== 'AI',1,0)),
    # trial[c("Addisons_disease", "gender", "Age_at_enrolment")],
    method = glm,
    y = AI_recoded,
    method.args = list(family = binomial),
    exponentiate = TRUE
  )

```



```{r, message = FALSE, cache = TRUE, warning=FALSE, echo = FALSE, results='asis'}
table_6 <- table_5 %>%
  mutate(Duration_of_current_illness = `Duration of current illness, median (IQR) (days)`/10) %>%
  # mutate(HIV_duration = as.numeric(as.Date(`Date of enrolment in study`, format='%m/%d/%Y') - as.Date(`HIV, when diagnosed`, format='%m/%d/%Y')),
  #   `mortality with Addisons disease` = ifelse(mortality == 1, 'yes', 'no'),
  #   gender = factor(gender, labels = c("Females", "Males")),
  #   Ethnicity = ifelse(Ethnicity == "Asian" | Ethnicity == "Coloured" | Ethnicity == "White", "Other", Ethnicity)
  # ) %>%
  dplyr::select(#Random_cortisol = `Random_cortisol`, Basal_cortisol = `Basal cortisol`, Stimulated_cortisol = `Stimulated cortisol`, `ACTH`, 
    BP_diastolic = `BP (diastolic)`, Weakness, Diarrhoea, `Tuberculosis`, Sodium = `Sodium mmol/L`,  Lymphocyte_count = `Lymphocyte count X109`, AI_recoded, Weight_loss=`Weight loss`, Anorexia, Neutrophils, `Total CD4 count`, Potassium = `Potassium mmol/L`, Duration_of_current_illness, Age_at_enrolment = `Age at enrolment`, Gender = `Gender, n(%)`#`Other`, 
) %>%
  filter(!is.na(AI_recoded))
nr_imputations <- 5
imputedData <- mice::mice(
  data = data.frame(table_6),
  m = nr_imputations,
  maxit = 20,
  defaultMethod = c("pmm", "logreg", "polyreg", "polr"), seed = 33
)

completeData_AI <- bind_cols(table_3 %>% 
                            dplyr::select(mortality, ttdeath, AI_recoded, 
                                          Gender, Ethnicity, ART_exposure = `ART exposure`, Kidney_medication = `Kidney medication`), 
                          aggregate(complete(imputedData, 'long')[,3:15], 
                                        by = list(complete(imputedData, 'long')$.id),
                                        FUN= mean)) %>%
                mutate(AI = ifelse(AI_recoded...3 =='AI', 1, 0)) %>%
  mutate(CD4_count = `Total.CD4.count`)
model4 <- glm(AI ~ Potassium + Neutrophils + CD4_count,#CD4_count,#ACTH + Random_cortisol + Lymphocyte_count,#ACTH + Stimulated_cortisol + BP_diastolic,
                                                 family = binomial(link = "logit"),
              data = completeData_AI) %>%
  tbl_regression(exponentiate = TRUE)
model4

```

